TEXTS = {
    "en": {
        "welcome": "Welcome!",
        "menu_title": "Menu. Choose an action:",
        "mode_usage": "Usage: /mode rss OR /mode creator OR /mode both",
        "payment_offer":
            "💳 Access pricing (USD/month):\n\n"
            "RSS mode (account-wide daily limit shared across all your channels):\n"
            "• 5 posts/day — $3/month\n"
            "• 10 posts/day — $5/month\n"
            "• 20 posts/day — $8/month\n• 40 posts/day — $12/month\n\n"
            "Creative mode (account-wide monthly post pool shared across all your channels):\n"
            "• 30 posts/month — $5/month\n"
            "• 60 posts/month — $8/month\n"
            "• 100 posts/month — $13/month\n• 200 posts/month — $20/month\n\n"
            "Channel slots are purchased separately (how many channels you can connect).\n"
            "You can combine RSS + Creative access.\n"
            "To activate, message: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Discount for upfront payment\n\n"
            "• 3 months — −10%\n"
            "• 6 months — −20%",
        "btn_modes": "🧠 Modes",
        "btn_scheduling": "🕒 Scheduling",
        "modes_title": "🧠 Modes. Choose a mode settings section:",
        "mode_rss_ai": "📰 RSS + AI",
        "mode_creative": "✨ Creative",
        "creative_locked": "🔒 Creative mode is unavailable for your account.",
        "rss_locked": "🔒 RSS + AI mode is unavailable for your account.",
        "creative_paywall":
            "Creative mode pricing (USD/month):\n"
            "(Account-wide monthly post pool shared across all connected channels)\n"
            "• 30/month — $5/month\n"
            "• 60/month — $8/month\n"
            "• 100/month — $13/month\n• 200/month — $20/month\n\n"
            "Channel slots are managed separately.\n"
            "To activate, message: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Discount for upfront payment\n\n"
            "• 3 months — −10%\n"
            "• 6 months — −20%",
        "rss_paywall":
            "RSS mode pricing (USD/month):\n"
            "(Account-wide daily limit shared across all connected channels)\n"
            "• 5/day — $3/month\n"
            "• 10/day — $5/month\n"
            "• 20/day — $8/month\n• 40/day — $12/month\n\n"
            "Channel slots are managed separately.\n"
            "To activate, message: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Discount for upfront payment\n\n"
            "• 3 months — −10%\n"
            "• 6 months — −20%",
        "mode_set_rss": "✅ Mode set: 📰 RSS + AI",
        "mode_set_creator": "✅ Mode set: ✨ Creative",
        "btn_payment": "💳 Buy posting plan",
        "btn_back": "⬅ Back",
        "btn_back_main": "⬅ Back to Main Menu",
        "btn_autopost_on": "🤖 Autopost: ON",
        "btn_autopost_off": "🤖 Autopost: OFF",
        "setup_menu_title": "⚙️ Setup:",
        "scheduling_menu_title": "🕒 Scheduling:",
        "channel_management_title": "📺 Channel management:",
        "modes_menu_title": "🧠 Modes settings:",
        "creative_menu_title": "✨ Creative mode\n\nSimple path:\n1) Understand your channel\n2) Build and use your idea bank\n3) Run focused campaigns\n4) Configure publishing\n5) Check Preview before posting",
        "rss_menu_title": "📰 RSS + AI settings\n\nStart path:\n1) Add first feed\n2) Set or confirm prompt/style\n3) Configure posting mode + timezone\n4) Enable posting\n5) Run Preview",
        "rss_primary_next_feed": "👉 Most important now: add your first feed. You can fine-tune format and extras later.",
        "rss_primary_next_prompt": "👉 Great, source is connected. Next: set or confirm your prompt/style.",
        "rss_primary_next_schedule": "👉 Next: open Scheduling, choose posting mode, and confirm timezone.",
        "rss_primary_next_enable": "👉 Setup is almost done. Turn posting ON when ready.",
        "rss_primary_next_preview": "✅ Bot is configured. Use Preview to verify output and keep Status handy.",
        "rss_quickstart_title": "🚀 RSS Quickstart",
        "rss_quickstart_intro": "Follow this lightweight guided path. You can return to advanced settings anytime.",
        "rss_quickstart_next_hint": "Tap the next unfinished step below.",
        "quickstart_step_channel": "Choose the channel for this setup",
        "quickstart_step_feed": "Add first feed",
        "quickstart_step_prompt": "Set or confirm prompt/style",
        "quickstart_step_mode": "Choose simple posting mode (recommended)",
        "quickstart_step_timezone": "Confirm timezone",
        "quickstart_step_enable": "Enable posting",
        "quickstart_step_preview": "Run preview or check live status",
        "quickstart_simple_mode_set": "✅ Simple mode is set to Interval. Next: confirm timezone, then enable posting.",
        "schedule_mode_title_rss": "📰 RSS + AI scheduling",
        "schedule_mode_title_creative": "✨ Creative scheduling",
        "schedule_guided_intro":
            "Set this in order:\n"
            "1) Choose posting mode\n"
            "2) Set slots (Edit Schedule) or interval\n"
            "3) Add blocked hours if needed\n"
            "4) Set freshness window\n"
            "5) Confirm timezone\n"
            "6) Turn posting ON\n\n"
            "Tips:\n"
            "• Interval works best for active feeds.\n"
            "• Scheduled Times works best for fixed publishing windows.\n"
            "• Too many limits can delay useful posts.",
        "schedule_current": "Current schedule:\n{schedule}",
        "schedule_input_instructions": "Send posting times in 24h format, comma-separated.\nExamples:\n09:00\n09:00, 15:00, 21:30\n\nSend \"clear\" to remove all slots.",
        "schedule_invalid": "❌ Invalid format. Use HH:MM or HH:MM, HH:MM",
        "schedule_saved": "✅ Schedule saved.",
        "schedule_cleared": "✅ Schedule cleared.",
        "schedule_enabled": "✅ Posting is now LIVE.",
        "schedule_disabled": "⏸ Posting is now OFF.",
        "schedule_posting_mode": "Posting mode: {mode}",
        "posting_mode_scheduled": "Scheduled Times",
        "posting_mode_interval": "Interval",
        "posting_mode_scheduled_set": "✅ Posting mode set to Scheduled Times.",
        "posting_mode_interval_set": "✅ Posting mode set to Interval.",
        "schedule_interval_current": "Check interval: every {interval} min",
        "schedule_freshness_current": "Post freshness: {minutes} min",
        "schedule_empty_slots": "(not set)",
        "schedule_not_set": "not set",
        "schedule_blocked_hours_off": "OFF",
        "schedule_status_on": "LIVE",
        "schedule_status_off": "OFF",
        "schedule_times_empty": "(empty)",
        "schedule_summary_channel": "• Channel: {channel}",
        "schedule_summary_mode": "• Posting mode: {mode}",
        "schedule_summary_slots": "• Schedule / interval: {slots}",
        "schedule_summary_timezone": "• Timezone: {timezone}",
        "schedule_summary_blocked": "• Blocked hours: {blocked}",
        "schedule_summary_freshness": "• Freshness: {minutes} min",
        "schedule_summary_status": "• Live state: {status}",
        "schedule_summary_next_run": "• Next run: {next_run}",
        "schedule_summary_title": "Current setup:",
        "activation_blocked_intro": "You cannot enable posting yet:",
        "activation_issue_channel": "No channel selected. Connect a channel first.",
        "activation_issue_feeds": "No feeds added. Add at least one RSS feed.",
        "activation_issue_timezone": "Timezone is not set. Open Scheduling → Timezone.",
        "activation_issue_posting_mode": "Posting mode is not configured. Choose Interval or Scheduled Times.",
        "activation_issue_slots": "Scheduled mode has no valid time slots.",
        "activation_warning_intro": "⚠️ Your setup may result in very few or no posts:",
        "activation_warn_blocked_hours": "Blocked hours cover about {hours}h/day, so many checks are skipped.",
        "activation_warn_freshness": "Freshness is {minutes} min, which may skip most feed items.",
        "activation_warn_interval": "Interval is every {interval} min, so checks are rare.",
        "activation_warn_slots_count": "Only one schedule slot is set, so posting windows are very limited.",
        "activation_warn_slots_gap": "Large schedule gaps (up to {hours}h) can delay posts.",
        "activation_warn_low_volume_interval": "Estimated possible checks per day: {count}.",
        "activation_off_confirmed": "🛑 Autopost is OFF.",
        "live_title": "✅ Autopost is LIVE",
        "live_line_channel": "Channel: {channel}",
        "live_line_mode": "Mode: {mode}",
        "live_line_schedule": "Posting: {schedule}",
        "live_line_interval": "every {interval} min",
        "live_line_timezone": "Timezone: {timezone}",
        "live_line_freshness": "Freshness: {minutes} min",
        "live_line_blocked": "Blocked hours: {blocked}",
        "live_line_next_check": "Next check: {next_run}",
        "live_line_next_post_hint": "Next possible post: depends on feed availability.",
        "status_live_title": "📡 Live autopost state",
        "status_live_mode_section": "Mode: {mode}",
        "preview_no_feeds": "No feeds. Add one first: /addfeed <url>",
        "preview_no_items_warning": "⚠️ No new unseen items found.\nThis is normal if:\n- feed has already been processed\n- no new posts yet\n\nTry again later or add another feed.",
        "preview_empty_no_feed": "No feed connected for this channel yet.\n\nNext step:\n• add your first feed\n• then run Preview again",
        "preview_empty_feed_no_items": "Feed is connected, but there are no readable items right now.\n\nNext step:\n• try another source\n• or check again later",
        "preview_empty_all_processed": "No unseen items right now — this is often normal.\nThe feed may be already processed or nothing new is published yet.\n\nNext step:\n• try again later\n• or add one more feed",
        "preview_empty_filtered": "Items were found, but none passed current freshness/relevance rules.\n\nNext step:\n• check if the feed has recent posts\n• increase freshness window or try another source",
        "preview_fallback_text_only": "Could not build image preview, so text preview is shown below.",
        "preview_temporarily_unavailable": "Preview is temporarily unavailable for this setup.",
        "preview_stage_config_failed": "Could not load the selected mode/channel for preview.",
        "preview_stage_rss_failed": "Could not fetch an RSS item for preview.",
        "preview_stage_ai_failed": "Could not generate preview text. Check the AI model and API key.",
        "preview_stage_image_failed": "Could not build the preview image.",
        "preview_stage_send_failed": "Could not send the preview to Telegram.",
        "preview_loading": "Preparing preview, this may take a few seconds.",
        "preview_status_template_build_failed_normal": "Could not build the template image. Showing normal preview.",
        "preview_status_no_rss_image_text_only": "No usable RSS image was found. Showing text preview.",
        "preview_status_asset_load_failed_normal": "Could not load the template or watermark. Showing normal preview.",
        "feed_management_title": "🧾 Feed management:",
        "feed_management_help": "Tip: Send a direct RSS URL, or send an X/Twitter profile link and the bot will create RSS automatically.",
        "feed_limit_status": "Feeds used: {count}/{limit}",
        "feed_name_prompt": "Send a short name for this feed, or send \"-\" to skip.",
        "feed_processing": "⏳ Checking and adding your feed...",
        "feed_recovery_invalid": "This link doesn't look like a valid RSS feed.\n\nTry this:\n• send a direct RSS/XML URL\n• or send an X profile link (example: https://x.com/username)",
        "feed_recovery_x_transform_failed": "I couldn't convert this X/Twitter profile into a readable RSS feed right now.\n\nTry this:\n• send another profile link\n• or send a direct RSS URL",
        "feed_recovery_x_status": "This looks like a post/status link.\n\nWhat to try next:\n• send the profile link instead\nExample: https://x.com/username",
        "feed_recovery_x_profile_invalid": "This X/Twitter profile link could not be recognized.\n\nWhat to try next:\n• send only the profile URL\nExample: https://x.com/username",
        "feed_recovery_empty": "This feed exists, but currently has no readable items.\n\nTry this:\n• use another source\n• or check again later",
        "feed_recovery_unreachable": "I couldn't reach this feed right now.\n\nTry this:\n• open the link in your browser\n• try again in a few minutes",
        "feed_recovery_unsupported": "This page is reachable, but it does not return a supported RSS/Atom format.\n\nWhat to try next:\n• send a direct RSS/XML feed URL\n• or choose another source",
        "rss_first_success_feed": "✅ First source connected.\nNext: set your style prompt, then choose schedule + timezone.\nRun Preview before going live.",
        "btn_lang": "🌐 Language",
        "choose_lang": "Choose your language:",
        "btn_setup": "🛠 Setup",
        "btn_help": "❓ Help",
        "help_link": "https://telegra.ph/Instructions-on-how-to-use-the-bot-and-additional-materials-02-27",
        "help_open_link": "Open this link:",
        "help_contact": "If something is unclear, contact me.",
        "btn_status": "ℹ️ Status",
        "btn_channel_management": "📺 Channel Management",
        "btn_add_channel": "➕ Add Channel",
        "btn_delete_channel": "🗑 Delete Channel",
        "btn_setchannel": "📌 Set channel",
        "btn_unsetchannel": "🧹 Unset channel",
        "btn_addfeed": "🧾 Add feed",
        "btn_deletefeed": "🗑 Delete feed",
        "btn_add_feed": "➕ Add Feed",
        "btn_delete_feed": "🗑 Delete Feed",
        "btn_edit_prompt": "✍️ Set style",
        "btn_channel_intake": "🧭 Understand Channel",
        "btn_channel_intake_fast_start": "⚡ Fast start",
        "btn_channel_intake_start": "🚀 Start guided setup",
        "btn_channel_intake_view": "📋 View channel context",
        "btn_campaigns": "📈 Campaigns",
        "btn_campaign_create": "➕ Create campaign",
        "btn_campaign_view": "📋 View campaigns",
        "btn_campaign_activate": "🎯 Set active campaign",
        "btn_creative_publish_settings": "⚙️ Publishing settings",
        "btn_build_prompt_ai": "🪄 Guided Prompt Builder",
        "btn_copy_my_style": "🎭 Copy style",
        "btn_content_plan": "🗂 Content Plan",
        "btn_source_center": "🧠 Source Center",
        "btn_topic_pillars": "🧱 Topic Pillars (Main Themes)",
        "btn_idea_bank": "💡 Idea Bank (Quick Ideas)",
        "btn_inspiration_links": "🔗 Inspiration Links",
        "btn_source_snippets": "📝 Source Snippets (Notes/Quotes)",
        "btn_view_items": "📋 View",
        "btn_add_item": "➕ Add",
        "btn_idea_generate": "🪄 Generate ideas",
        "btn_delete_item": "🗑 Delete",
        "btn_content_plan_generate": "🗓 Generate 7-day Plan",
        "btn_content_plan_view": "📋 View Plan",
        "btn_content_plan_regenerate_item": "🔄 Regenerate Item",
        "btn_content_plan_edit_item": "✍️ Edit Item",
        "btn_preview": "🧪 Preview",
        "btn_pause_posting": "⏸ Pause Posting",
        "btn_resume_posting": "▶️ Resume Posting",
        "btn_content_variety": "🎛 Content Variety",
        "btn_visual_support": "🖼 Visual Support",
        "btn_visual_generate_idea": "🧩 Generate Visual Idea",
        "btn_visual_generate_search_query": "🔎 Generate Search Query",
        "btn_visual_generate_ai_prompt": "🎨 Generate AI Image Prompt",
        "btn_variation_level": "Variation Level",
        "btn_post_types": "Post Types",
        "btn_avoid_repetition_on": "♻️ Avoid Repetition: ON",
        "btn_avoid_repetition_off": "♻️ Avoid Repetition: OFF",
        "btn_edit_feeds": "🧾 Edit Feeds",
        "btn_rss_quickstart": "🚀 Quickstart",
        "btn_quickstart_add_feed": "1) Add first feed",
        "btn_quickstart_set_prompt": "2) Set style",
        "btn_quickstart_simple_mode": "3) Simple mode",
        "btn_quickstart_timezone": "4) Timezone",
        "btn_quickstart_enable": "5) Enable posting",
        "btn_quickstart_preview": "6) Preview / status",
        "btn_rss_output_settings": "🧩 Post Format",
        "btn_post_format": "🧩 Post Format",
        "rss_output_settings_title": "🧩 Post format settings (RSS + AI):",
        "creative_output_settings_title": "🧩 Post format settings (Creative):",
        "post_format_assets_info": "Visual assets:\n• Template image: {template}\n• Watermark: {watermark}\n• Bold title: {bold_title}\n• Custom emoji: {emoji}\n\nTemplate image = your background/frame for branded visuals.\nWatermark = your logo or channel mark placed on top.\nRecommended: JPG/PNG template, PNG watermark (transparent if possible).\nAuto composition applies when RSS item has an image.",
        "status_added": "added",
        "status_not_added": "not added",
        "btn_edit_template_image": "🖼 Edit template",
        "btn_edit_watermark": "🏷 Edit watermark",
        "btn_add_asset": "➕ Add",
        "btn_replace_asset": "♻️ Replace",
        "btn_delete_asset": "🗑 Delete",
        "asset_manage_template_title": "🖼 Template management",
        "asset_manage_watermark_title": "🏷 Watermark management",
        "asset_manage_template_help": "Here you can manage your template image.",
        "asset_manage_watermark_help": "Here you can manage your watermark.",
        "asset_manage_status": "Current status: {status}",
        "asset_prompt_send_template": "Send one image for the template/background (photo or image document).\nBest result: use a wide high-quality image.",
        "asset_prompt_send_watermark": "Send one image for the watermark/logo (photo or image document).\n\nTip: You can remove the background here: https://www.remove.bg/\nBest result: PNG, preferably sent as a document. A slightly transparent watermark usually looks better.",
        "asset_saved_template": "✅ Template image saved.",
        "asset_saved_watermark": "✅ Watermark saved.",
        "asset_deleted_template": "✅ Template image deleted.",
        "asset_deleted_watermark": "✅ Watermark deleted.",
        "asset_upload_invalid": "Please send an image as a photo or image document.",
        "asset_upload_error": "❌ Could not save the image. Please try again.",
        "btn_source_link_on": "🔗 Source Link: ON",
        "btn_source_link_off": "🔗 Source Link: OFF",
        "btn_feed_image_on": "🖼 Feed Image: ON",
        "btn_feed_image_off": "🖼 Feed Image: OFF",
        "btn_rss_cta_on": "📣 CTA: ON",
        "btn_rss_cta_off": "📣 CTA: OFF",
        "btn_bold_title_on": "🅱️ Bold title: ON",
        "btn_bold_title_off": "🅱️ Bold title: OFF",
        "btn_emoji_management": "✨ Emoji management",
        "btn_add_emoji": "✨ Add emoji",
        "btn_add_update_emoji": "✨ Add / update emoji",
        "btn_delete_emoji": "🗑 Delete emoji",
        "emoji_management_title": "✨ Emoji management",
        "emoji_management_status": "Saved emoji: {emoji}\nSaved link: {link}",
        "status_yes": "yes",
        "status_no": "no",
        "emoji_prompt_send": "You can send a link to an emoji pack/source or just send one or several emoji in a message (including premium/custom). Link is saved as reference only.",
        "emoji_saved": "✅ Emoji style saved.",
        "emoji_deleted": "✅ Emoji style deleted.",
        "channel_saved_named": "✅ Channel saved: {channel}",
        "channel_forward_invalid": "I couldn't detect a channel from this message. Please forward a post from your channel after adding the bot as admin.",
        "channel_forward_admin_missing": "Channel detected, but bot is not an admin there. Add admin rights and forward a channel post again.",
        "channel_forward_access_error": "Channel detected, but I couldn't verify access. Make sure the bot is channel admin and forward another channel post.",
        "rss_cta_prompt": "Send the CTA text in one message. It will be appended to every RSS post when CTA is ON.",
        "rss_cta_saved": "✅ CTA text saved.",
        "rss_posting_paused_short": "RSS paused",
        "rss_posting_resumed_short": "RSS resumed",
        "rss_posting_paused_notice": "⏸ Pause stops automatic RSS posting temporarily.",
        "rss_posting_resumed_notice": "▶️ Resume re-checks RSS candidates and does not auto-post outdated missed items.",
        "btn_schedule_rss": "📰 RSS + AI Schedule",
        "btn_schedule_creative": "✨ Creative Schedule",
        "btn_schedule_edit": "✍️ Edit Schedule",
        "btn_schedule_edit_interval": "⏱ Edit Interval",
        "btn_schedule_quiet_hours": "🌙 Blocked hours",
        "btn_schedule_freshness": "🕰 Post freshness",
        "btn_quiet_hours_add": "➕ Add quiet hours",
        "btn_quiet_hours_delete": "🗑 Delete quiet hours",
        "btn_posting_mode_scheduled": "🔁 Mode: Scheduled Times",
        "btn_posting_mode_interval": "🔁 Mode: Interval",
        "btn_schedule_toggle_on": "✅ Turn ON",
        "btn_schedule_toggle_off": "⏸ Turn OFF",
        "interval_input_instructions": "Send interval in minutes (numbers only).\nExamples: 60, 120, 180\n\nSend \"cancel\" to go back.",
        "interval_invalid": "❌ Invalid interval. Send a whole number in minutes (for example: 60).",
        "interval_saved": "✅ Interval saved: every {interval} min.",
        "quiet_hours_management_title": "🌙 Blocked hours",
        "quiet_hours_list_title": "Saved blocked-hour windows:",
        "quiet_hours_empty": "No blocked-hour windows yet.",
        "quiet_hours_input_instructions": "Send blocked time in 24-hour format:\nHH:MM-HH:MM\nExamples:\n- 12:00-13:00\n- 23:30-08:00\nOvernight ranges are allowed.\nSend \"cancel\" to go back.",
        "quiet_hours_invalid": "❌ Invalid format. Use HH:MM-HH:MM (for example: 12:00-13:00 or 23:30-08:00).",
        "quiet_hours_saved": "✅ Blocked-hour window added: {start}-{end}",
        "quiet_hours_deleted": "✅ Blocked-hour window deleted: {window}",
        "quiet_hours_delete_empty": "There are no blocked-hour windows to delete.",
        "schedule_timezone": "Timezone: {timezone}",
        "btn_schedule_timezone": "🌐 Timezone",
        "timezone_input_instructions": "Set timezone for the selected channel.\nUse UTC+2, UTC-5, +3, -4, or 0.\nSend \"cancel\" to go back.",
        "timezone_autodetected_notice": "✅ Channel timezone auto-set to {timezone} (inherited from your previous settings).",
        "timezone_fallback_notice": "ℹ️ Could not reliably detect timezone, so fallback {timezone} was saved. You can change it anytime.",
        "freshness_input_instructions": "Send freshness threshold in minutes (15..1440).\nOlder items will be skipped.\nSend \"cancel\" to go back.",
        "freshness_invalid": "❌ Invalid freshness value. Send a whole number from 15 to 1440.",
        "freshness_saved": "✅ Freshness threshold saved: {minutes} min.",
        "timezone_invalid": "❌ Invalid timezone. Use UTC+0, UTC+2, UTC-5, +3, -4, or 0.",
        "timezone_saved": "✅ Timezone saved: {timezone}",
        "variation_level_title": "🎚 Variation level. Choose one:",
        "variation_level_value_low": "Low",
        "variation_level_value_balanced": "Balanced",
        "variation_level_value_high": "High",
        "post_types_title": "🧩 Post types. Enable one or more:",
        "post_type_educational": "Educational",
        "post_type_opinion": "Opinion",
        "post_type_story": "Story",
        "post_type_checklist": "Checklist",
        "post_type_question": "Question",
        "post_type_myth_vs_fact": "Myth vs Fact",
        "post_type_mini_case": "Mini Case",
        "creative_variety_title": "🎛 Content Variety",
        "creative_variety_intro": "Change how repetitive or diverse your posts feel.\nUse this if you want more variety in formats and angles.",
        "creative_variety_note": "These controls add lightweight diversity while keeping your Creative prompt as the main instruction.",
        "creative_publish_settings_title": "⚙️ Creative publishing settings",
        "channel_intake_title": "🧭 Understand Channel",
        "channel_intake_intro": "Teach the bot about your channel with practical details. This becomes the strategic base for ideas, campaigns, and post generation.",
        "channel_intake_start": "Great — short and specific answers work best. Usually 1–3 sentences are enough.\nSend \"cancel\" anytime.",
        "channel_intake_empty": "No channel context saved yet. Start guided setup.",
        "channel_intake_saved": "✅ Channel context saved.",
        "channel_intake_cancelled": "Channel setup cancelled.",
        "channel_intake_q_channel_about": "What is your channel about?\nWhy: this defines your main content direction.\nGood answer: niche + who it helps + promise. 1–3 sentences.\nExample: 'Channel for beginner freelancers. We share practical client-finding scripts and weekly growth tips.'",
        "channel_intake_q_audience": "Who is your audience?\nWhy: content works better when written for a specific person.\nGood answer: role, level, and context. Be specific, 1–3 sentences.\nExample: 'Beginner experts on Telegram, 22–35, already posting but struggling with consistency.'",
        "channel_intake_q_audience_wants": "What does your audience want most right now?\nWhy: this helps prioritize post angles.\nGood answer: top 1–3 outcomes they are trying to get.\nExample: 'Get first paying clients and build stable inbound leads this month.'",
        "channel_intake_q_audience_pains": "What problems block them?\nWhy: strong posts usually solve specific pains.\nGood answer: concrete blockers, fears, or mistakes.\nExample: 'No clear offer, low reach, and fear of sounding pushy in sales posts.'",
        "channel_intake_q_tone_style": "What tone/style should posts use?\nWhy: this keeps output on-brand.\nGood answer: 2–4 style traits + what to avoid.\nExample: 'Practical, direct, supportive. No hype, no manipulative pressure.'",
        "channel_intake_q_offers": "What do you sell or promote?\nWhy: content should naturally lead to your offer.\nGood answer: product/service + format + price range if relevant.\nExample: '1:1 launch consulting, 4-week group program, and a $49 mini-course.'",
        "channel_intake_q_creator_goals": "What are your content goals for the next few weeks?\nWhy: this sets conversion priorities.\nGood answer: 1–2 measurable goals.\nExample: 'Book 10 discovery calls and warm audience for a group program launch.'",
        "channel_intake_q_good_posts": "Share good post examples you want more of.\nWhy: examples help replicate winning patterns.\nGood answer: 1–3 examples with a short note why they worked.\nExample: 'Case-study posts with clear lesson and CTA to DM for details.'",
        "channel_intake_q_bad_posts": "Share bad/unwanted post examples.\nWhy: this prevents weak outputs.\nGood answer: 1–3 examples + what felt wrong.\nExample: 'Generic motivational posts — high views but no replies or leads.'",
        "channel_intake_q_never_sound_like": "How should the channel never sound?\nWhy: this protects brand trust.\nGood answer: words/tones to avoid.\nExample: 'Never arrogant, never manipulative, never fake urgency.'",
        "channel_intake_label_channel_about": "Channel",
        "channel_intake_label_audience": "Audience",
        "channel_intake_label_audience_wants": "Audience wants",
        "channel_intake_label_audience_pains": "Audience pains",
        "channel_intake_label_tone_style": "Tone/style",
        "channel_intake_label_offers": "Offers",
        "channel_intake_label_creator_goals": "Goals",
        "channel_intake_label_good_posts": "Good examples",
        "channel_intake_label_bad_posts": "Bad examples",
        "channel_intake_label_never_sound_like": "Never sound like",
        "idea_bank_generating": "⏳ Generating ideas from your channel context...",
        "idea_bank_generated": "✅ Added {count} ideas to your bank.",
        "campaigns_intro": "Build campaign arcs with clear goals and conversion flow.",
        "campaign_create_start": "Let's create a campaign.\nAnswer step by step. Send \"cancel\" anytime.",
        "campaign_create_saved": "✅ Campaign created and set active.",
        "campaign_create_cancelled": "Campaign creation cancelled.",
        "campaign_empty": "No campaigns yet. Create your first campaign.",
        "campaign_list_title": "📈 Saved campaigns:",
        "campaign_activate_prompt": "Send the campaign number to activate:",
        "campaign_activate_invalid": "Could not find that campaign number.",
        "campaign_activate_saved": "✅ Active campaign updated.",
        "campaign_active_label": "🎯 Active campaign: {name}",
        "campaign_q_goal": "What is the campaign goal?\nWhy it matters: goal defines the whole sequence.\nGood answer: one concrete business result.\nExample: 'Get 20 demo calls for my design service in 10 days.'",
        "campaign_q_offer": "What exactly are you promoting/selling?\nWhy it matters: message clarity depends on offer clarity.\nGood answer: what it is, for whom, and format.\nExample: '4-week content mentorship for experts who sell through Telegram.'",
        "campaign_q_duration": "Campaign duration in days.\nWhy it matters: pace depends on timeline.\nGood answer: one number (3, 5, 7, 14...).\nExample: '7'",
        "campaign_q_target_action": "What exact action should people take?\nWhy it matters: each day should move toward this action.\nGood answer: one observable action.\nExample: 'Send \"START\" in DM to get onboarding details.'",
        "campaign_q_awareness": "What is audience awareness/current situation?\nWhy it matters: determines whether to educate or convert faster.\nGood answer: what they already know and where they are now.\nExample: 'They know they need content, but think daily posting is too hard.'",
        "campaign_q_objections": "Main objections to handle?\nWhy it matters: objections block conversion.\nGood answer: 2–5 real objections.\nExample: 'Too expensive, no time, unsure this works in my niche.'",
        "campaign_q_benefits": "Main benefits to emphasize?\nWhy it matters: these become your daily value angles.\nGood answer: 2–5 practical outcomes.\nExample: 'Clear content system, faster post creation, more qualified inbound leads.'",
        "campaign_q_urgency": "Any urgency / launch / event context?\nWhy it matters: helps choose CTA intensity.\nGood answer: date/window or reason to act now.\nExample: 'Enrollment closes Friday at 21:00 UTC.'",
        "quickstart_start": "⚡ Fast start (about 2 minutes).\nWe will answer 4 essentials and generate your first strategic preview post.",
        "quickstart_cancelled": "Fast start cancelled.",
        "quickstart_q_channel_about": "What is your channel about?\n1–2 concrete sentences.\nExample: 'Practical content strategy for experts selling via Telegram.'",
        "quickstart_q_audience": "Who is your audience?\nBe specific (role/level).\nExample: 'Coaches and consultants with small Telegram channels.'",
        "quickstart_q_offer": "What do you sell or promote?\nExample: '1:1 strategy sessions and a 4-week group program.'",
        "quickstart_q_goal": "What is your current goal?\nExample: 'Get 8 discovery calls this month.'",
        "quickstart_saved": "✅ Fast setup saved. Your channel now has enough context for better content generation.",
        "quickstart_why_post": "Why this first post: it gives quick relevance to your audience, connects naturally to your offer, and creates a clear next action.",
        "quickstart_preview_title": "🧪 Strategic preview post:",
        "quickstart_preview_failed": "⚠️ Could not generate preview right now, but your quick profile is saved. Tap Preview to try again.",
        "first_success_next_step_quickstart": "Next best step: add audience pains and objections in guided setup, then generate another preview or create a campaign.",
        "first_success_next_step_campaign": "Your channel now has enough context for better content generation. Next, you can improve results by adding more audience pains or objections.",
        "campaign_created_for_goal": "Campaign goal: {goal}",
        "campaign_fallback_goal": "Campaign",
        "campaign_arc_title": "🗺 Campaign sequence:",
        "campaign_arc_empty": "Campaign arc is saved, but detailed day-by-day sequence is not available yet.",
        "campaign_arc_default_stage": "Stage",
        "campaign_arc_default_direction": "Direction",
        "campaign_arc_default_hook": "Practical opening angle",
        "campaign_arc_cta_optional": "Soft CTA or engagement CTA",
        "campaign_arc_day_block": "Day {day}\n• Stage purpose: {stage}\n• Suggested angle: {hook}\n• Post direction: {direction}\n• CTA / conversion role: {cta}",
        "creative_variety_summary": "Level: {level}\nPost types: {post_types}\nAvoid repetition: {avoid}",
        "creative_visual_support_title": "🖼 Visual Support",
        "creative_visual_support_intro": "Get ideas for visuals, search phrases, or AI image prompts.\nUse this if you want matching images for your posts.",
        "creative_visual_generating_idea": "Generating visual idea...",
        "creative_visual_generating_search_query": "Generating search query...",
        "creative_visual_generating_ai_prompt": "Generating AI image prompt...",
        "creative_visual_topic_fallback": "No current topic found in your content plan yet. Using your saved Creative prompt.",
        "creative_visual_label_idea": "🧩 Visual idea",
        "creative_visual_label_search_query": "🔎 Search query",
        "creative_visual_label_ai_prompt": "🎨 AI image prompt",
        "creative_visual_error": "❌ Could not generate visual support right now. Please try again.",
        "content_plan_title": "🗂 Content Plan",
        "content_plan_intro": "Plan your posts for a few days in advance.\nUse this if you want a clearer weekly structure.",
        "content_plan_generating": "⏳ Generating 7-day content plan...",
        "content_plan_generated": "✅ 7-day plan saved.",
        "content_plan_current_title": "📋 Current weekly plan:",
        "content_plan_empty": "No plan yet. Tap “Generate 7-day Plan” to create one.",
        "content_plan_no_plan": "No saved plan found for this channel.",
        "content_plan_choose_regenerate": "Choose an item to regenerate:",
        "content_plan_choose_edit": "Choose an item to edit:",
        "content_plan_regenerating_item": "⏳ Regenerating selected item...",
        "content_plan_item_regenerated": "✅ Item regenerated.",
        "content_plan_edit_prompt": "Send replacement topic text for {day_label}.\nCurrent topic: {topic}\nCurrent angle: {angle}\n\nSend \"cancel\" to abort.",
        "content_plan_edit_cancelled": "Edit cancelled.",
        "content_plan_item_saved": "✅ Plan item updated.",
        "content_plan_item_line": "{idx}) {day_label}\nTopic: {topic}\nAngle: {angle}\nType: {post_type}\nGoal: {goal}\nStatus: {status}",
        "source_center_title": "🧠 Source Center",
        "source_center_intro": "Give the bot better materials for stronger posts.\n• Topic Pillars = your main channel themes\n• Idea Bank = quick post ideas\n• Inspiration Links = useful references\n• Source Snippets = notes, quotes, or copied text",
        "source_delete_choose": "Choose an item to delete:",
        "source_delete_empty": "No items yet. Add one first.",
        "source_add_cancelled": "Add cancelled.",
        "source_item_deleted": "✅ Deleted: {item}",
        "source_topic_pillars_title": "🧱 Topic Pillars (Main Themes)",
        "source_topic_pillars_empty": "No topic pillars yet.",
        "source_topic_pillars_add_prompt": "Send one topic pillar to add.\n\nExamples:\n• personal opinions\n• educational tips\n• behind the scenes\n\nSend \"cancel\" to go back.",
        "source_topic_pillars_saved": "✅ Topic pillar saved.",
        "source_idea_bank_title": "💡 Idea Bank (Quick Ideas)",
        "source_idea_bank_empty": "No ideas in the bank yet.",
        "source_idea_bank_add_prompt": "Send one idea to add.\n\nExamples:\n• Why creators burn out from copying trends\n• Small channels win by having strong opinions\n\nSend \"cancel\" to go back.",
        "source_idea_bank_saved": "✅ Idea saved.",
        "source_inspiration_links_title": "🔗 Inspiration Links",
        "source_inspiration_links_empty": "No inspiration links yet.",
        "source_inspiration_links_add_prompt": "Send one link to save for inspiration.\n\nSend \"cancel\" to go back.",
        "source_inspiration_links_saved": "✅ Inspiration link saved.",
        "source_source_snippets_title": "📝 Source Snippets (Notes/Quotes)",
        "source_source_snippets_empty": "No source snippets yet.",
        "source_source_snippets_add_prompt": "Send one snippet/note to save.\n\nSend \"cancel\" to go back.",
        "source_source_snippets_saved": "✅ Source snippet saved.",
        "label_on": "ON",
        "label_off": "OFF",
        "status_id": "ID",
        "status_channels": "Channels",
        "status_rss_daily": "RSS posts/day available",
        "status_creative_monthly_pool": "Creative monthly pool",
        "status_creative_monthly_used": "Creative posts used this month",
        "status_creative_monthly_remaining": "Creative posts remaining this month",
        "status_creative_monthly_period": "Creative pool period",
        "status_valid_until": "Subscription valid until",
        "posting_limit_reached": "Posting limit reached for the current period.",
        "creative_quota_title": "📦 Creative monthly quota",
        "creative_quota_pool": "• Monthly pool: {pool}",
        "creative_quota_used": "• Used this month: {used}",
        "creative_quota_remaining": "• Remaining this month: {remaining}",
        "creative_quota_period": "• Reset period: {period} (YYYY-MM)",
        "status_not_set": "not set",
        "status_inactive": "inactive",
        "status_title": "📊 Account status",
        "btn_setstyle": "✍️ Set style",
        "btn_showstyle": "📄 Show style",
        "btn_resetstyle": "♻️ Reset style",
        "btn_on": "🤖 Autopost ON",
        "btn_off": "🛑 OFF",
        "modes_help": "Choose mode with commands:\n/mode rss\n/mode creator\n/mode both",
        "prompt_current": "Current prompt:\n{prompt}",
        "prompt_current_rss": "Current RSS + AI prompt:\n{prompt}",
        "prompt_current_creative": "Current Creative prompt:\n{prompt}",
        "prompt_empty": "No prompt saved yet. The default style is used.",
        "style_setup_title": "Set style:",
        "style_setup_current_prefix": "Current prompt text:\n{prompt}",
        "style_setup_empty": "No prompt saved yet.",
        "style_setup_saved": "✅ Current prompt saved.",
        "prompt_edit_instructions": "Send your final prompt in one message. Send \"cancel\" to keep the current one.",
        "prompt_edit_cancel_hint": "Send \"cancel\" to keep the current prompt.",
        "prompt_guidance_creative": (
            "How to write a strong Creative prompt for Telegram:\n"
            "• Topic/niche: what exactly you post about.\n"
            "• Tone/voice: expert, friendly, bold, etc.\n"
            "• Audience: who reads your channel.\n"
            "• Length: typical size in lines/characters.\n"
            "• Structure: hook → key points → takeaway.\n"
            "• CTA: soft invite, question, DM, link, etc.\n"
            "• Avoid: clichés, clickbait, banned/off-topic themes.\n\n"
            "Template (copy and edit):\n"
            "You write Telegram posts for [niche].\n"
            "Tone: [tone/voice]. Audience: [target audience].\n"
            "Each post is about [length].\n"
            "Structure: 1) hook, 2) 2–4 practical points/examples, 3) concise conclusion, 4) CTA: [CTA style].\n"
            "Avoid: [what to avoid]."
        ),
        "prompt_guidance_rss": (
            "How to write a strong RSS + AI prompt for Telegram:\n"
            "• Transform feed content: rewrite in your own style, not copy-paste.\n"
            "• Tone/voice: professional, neutral, energetic, etc.\n"
            "• Summary style: brief digest or more detailed explanation.\n"
            "• Length: typical size in lines/characters.\n"
            "• Opinion: allow your commentary or keep neutral.\n"
            "• Ending/CTA: question, subscribe, share, none.\n"
            "• Avoid: fake facts, hype, repetition, overly long intros.\n\n"
            "Template (copy and edit):\n"
            "Rewrite RSS/news items into Telegram posts in [tone].\n"
            "Format: short hook + clear summary + key takeaway.\n"
            "Length: [length].\n"
            "Opinion mode: [neutral / add brief commentary].\n"
            "Ending: [CTA or no CTA].\n"
            "Avoid: [what to avoid]."
        ),
        "prompt_edit_cancelled": "Prompt unchanged.",
        "prompt_edit_saved": "✅ Prompt updated.",
        "prompt_builder_intro_creative": "🪄 Guided Prompt Builder (Creative)\n\nI will ask a few short questions and generate a polished Creative prompt for you.\n\nSend \"cancel\" anytime to exit.",
        "prompt_builder_intro_rss": "🪄 Guided Prompt Builder (RSS + AI)\n\nI will ask a few short questions and generate a polished RSS + AI prompt for you.\n\nSend \"cancel\" anytime to exit.",
        "prompt_builder_q_creative_1": "1/7 What is your niche/topic?\n\nExamples:\n• local football news\n• esports updates\n• nutrition for runners",
        "prompt_builder_q_creative_2": "2/7 Who is the target audience?\n\nExamples:\n• football fans\n• Barcelona supporters\n• general sports readers\n• casual Telegram audience",
        "prompt_builder_q_creative_3": "3/7 What tone should the posts have?\n\nExamples:\n• professional news style\n• friendly fan voice\n• neutral informative\n• energetic sports commentary",
        "prompt_builder_q_creative_4": "4/7 What types of posts do you want most?\n\nExamples:\n• quick news recaps\n• opinions\n• checklists\n• Q&A posts",
        "prompt_builder_q_creative_5": "5/7 What length should the posts usually be?\n\nFor example:\n• short (2–3 sentences)\n• medium (4–6 sentences)\n• up to ~100 words",
        "prompt_builder_q_creative_6": "6/7 What should be avoided?\n\nExamples:\n• clickbait\n• slang\n• political topics\n• aggressive wording",
        "prompt_builder_q_creative_7": "7/7 What language should the posts be in? (English/Russian)",
        "prompt_builder_q_rss_1": "1/7 What is the feed/topic about?\n\nExamples:\n• football transfer news\n• esports tournaments\n• startup funding",
        "prompt_builder_q_rss_2": "2/7 Who is the target audience?\n\nExamples:\n• football fans\n• Barcelona supporters\n• general sports readers\n• casual Telegram audience",
        "prompt_builder_q_rss_3": "3/7 What tone should the posts have?\n\nExamples:\n• professional news style\n• friendly fan voice\n• neutral informative\n• energetic sports commentary",
        "prompt_builder_q_rss_4": "4/7 What length should the posts usually be?\n\nFor example:\n• short (2–3 sentences)\n• medium (4–6 sentences)\n• up to ~100 words",
        "prompt_builder_q_rss_5": "5/7 Neutral summaries or a stronger rewritten angle?\n\nExamples:\n• mostly neutral digest\n• concise editorial spin",
        "prompt_builder_q_rss_6": "6/7 What should be avoided?\n\nExamples:\n• hype\n• duplicate phrases\n• too many hashtags\n• long intros",
        "prompt_builder_q_rss_7": "7/7 What language should the posts be in? (English/Russian)",
        "prompt_builder_generating": "⏳ Generating prompt...",
        "prompt_builder_review": "Here is your generated prompt:\n\n{prompt}\n\nSave it for this mode?",
        "prompt_builder_saved": "✅ Prompt saved for this mode.",
        "prompt_builder_cancelled": "Prompt builder cancelled. No changes saved.",
        "prompt_builder_error": "❌ Could not generate a prompt right now. Please try again.",
        "copy_style_intro": "Send me 3 posts from your channel.\nI will analyze the tone, wording, and structure and create a prompt in your style.",
        "copy_style_progress": "Got it. Send {left} more posts.",
        "copy_style_invalid": "Please send text posts so I can analyze your style.",
        "copy_style_success": "✅ Done. Prompt updated for this mode based on your style.",
        "copy_style_loading": "Got it. Preparing your prompt, this will take a few seconds.",
        "copy_style_review": "Your style-based prompt is ready.\n\n{prompt}\n\nBefore saving, you may want to add details like output language, post length, what to avoid, audience, CTA/ending, or whether to stay neutral vs add commentary.\nYou can save it now or edit it first. You can also copy the full prompt, adjust it, and send back the final version.",
        "copy_style_edit_ready": "Your generated draft is below. Edit it and send your final version:\n\n{prompt}",
        "btn_save": "💾 Save",
        "btn_edit": "✍️ Edit",
        "btn_regenerate": "🔄 Regenerate",
        "btn_cancel": "❌ Cancel",
        "feeds_empty": "No feeds yet.",
        "feed_added": "✅ Feed added.",
        "feed_deleted": "✅ Feed deleted.",
        "feed_duplicate": "This feed is already added for this channel.",
        "feed_read_failed": "Feed read failed. Send a valid RSS/Atom URL.",
        "feed_auto_failed": "Automatic RSS creation for this X/Twitter profile failed. Try another profile link or send a direct RSS URL.",
        "feed_x_profile_only": "Please send an X/Twitter profile URL (example: https://x.com/username), not a specific post URL.",
        "feed_limit_reached": "This channel includes up to {limit} feeds by default.\nTo use more feeds, extra feed access is required.",
        "channel_deleted": "✅ Channel removed.",
        "channel_empty": "No channel configured.",
        "channels_list_title": "Saved channels ({count}/{slots}):",
        "channels_empty_state": "No saved channels yet.\nSlots available: {slots}.",
        "channel_choose_delete": "Choose a channel to delete:",
        "channel_deleted_named": "✅ Channel removed: {channel}",
        "channel_slots_limit": "Channel limit reached ({count}/{slots}). Buy/add channel capacity to connect more channels.",
        "channel_picker_title": "Select channel to continue:",
        "channel_picker_empty": "No channels found yet. Add a channel first in Channel Management.",
        "channel_selected_now": "📌 Selected channel: {channel}",
        "start_welcome": (
            "👋 Welcome to Postora.\n\n"
            "I help you create and schedule posts for your Telegram channel.\n\n"
            "To begin, open ⚙️ Setup, choose a mode, connect your channel, and configure your prompt, feeds, and schedule.\n"
            "You can manage plans/payment separately anytime."
        ),
        "start_welcome_named": (
            "👋 Welcome, {name}!\n\n"
            "I help you create and schedule posts for your Telegram channel.\n\n"
            "To begin, open ⚙️ Setup, choose a mode, connect your channel, and configure your prompt, feeds, and schedule.\n"
            "You can manage plans/payment separately anytime."
        ),
    },
    "ru": {
        "welcome": "Добро пожаловать!",
        "menu_title": "Меню. Выберите действие:",
        "mode_usage": "Использование: /mode rss ИЛИ /mode creator ИЛИ /mode both",
        "payment_offer":
            "💳 Стоимость доступа (USD/месяц):\n\n"
            "RSS-режим (дневной лимит на аккаунт, общий для всех каналов):\n"
            "• 5 постов/день — $3/месяц\n"
            "• 10 постов/день — $5/месяц\n"
            "• 20 постов/день — $8/месяц\n• 40 постов/день — $12/месяц\n\n"
            "Creative-режим (месячный пул постов на аккаунт, общий для всех каналов):\n"
            "• 30 постов/месяц — $5/месяц\n"
            "• 60 постов/месяц — $8/месяц\n"
            "• 100 постов/месяц — $13/месяц\n• 200 постов/месяц — $20/месяц\n\n"
            "Слоты каналов покупаются отдельно (сколько каналов можно подключить).\n"
            "Можно комбинировать RSS + Creative доступ.\n"
            "Для активации напишите: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Скидка при оплате сразу\n\n"
            "• 3 месяца — −10%\n"
            "• 6 месяцев — −20%",
        "btn_modes": "🧠 Режимы",
        "btn_scheduling": "🕒 Расписание",
        "modes_title": "🧠 Режимы. Выберите раздел настроек:",
        "mode_rss_ai": "📰 RSS + AI",
        "mode_creative": "✨ Creative",
        "creative_locked": "🔒 Режим Creative недоступен для вашего аккаунта.",
        "rss_locked": "🔒 Режим RSS + AI недоступен для вашего аккаунта.",
        "creative_paywall":
            "Стоимость Creative-режима (USD/месяц):\n"
            "(Месячный пул постов на аккаунт, общий для всех подключённых каналов)\n"
            "• 30/месяц — $5/месяц\n"
            "• 60/месяц — $8/месяц\n"
            "• 100/месяц — $13/месяц\n• 200/месяц — $20/месяц\n\n"
            "Слоты каналов управляются отдельно.\n"
            "Для активации напишите: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Скидка при оплате сразу\n\n"
            "• 3 месяца — −10%\n"
            "• 6 месяцев — −20%",
        "rss_paywall":
            "Стоимость RSS-режима (USD/месяц):\n"
            "(Дневной лимит на аккаунт, общий для всех подключённых каналов)\n"
            "• 5/день — $3/месяц\n"
            "• 10/день — $5/месяц\n"
            "• 20/день — $8/месяц\n• 40/день — $12/месяц\n\n"
            "Слоты каналов управляются отдельно.\n"
            "Для активации напишите: @a_karaglan, @a_karaglanov\n\n"
            "🔻 Скидка при оплате сразу\n\n"
            "• 3 месяца — −10%\n"
            "• 6 месяцев — −20%",
        "mode_set_rss": "✅ Режим установлен: 📰 RSS + AI",
        "mode_set_creator": "✅ Режим установлен: ✨ Creative",
        "btn_payment": "💳 Купить пакет постов",
        "btn_back": "⬅ Назад",
        "btn_back_main": "⬅ В главное меню",
        "btn_autopost_on": "🤖 Автопост: ВКЛ",
        "btn_autopost_off": "🤖 Автопост: ВЫКЛ",
        "setup_menu_title": "⚙️ Настройка:",
        "scheduling_menu_title": "🕒 Расписание:",
        "channel_management_title": "📺 Управление каналом:",
        "modes_menu_title": "🧠 Настройки режимов:",
        "creative_menu_title": "✨ Creative-режим\n\nПростой путь:\n1) Понять канал\n2) Вести банк идей\n3) Запускать кампании\n4) Настроить публикации\n5) Проверить Превью перед запуском",
        "rss_menu_title": "📰 Настройки RSS + AI\n\nПуть запуска:\n1) Добавьте первую ленту\n2) Задайте или проверьте промпт/стиль\n3) Настройте режим публикации + часовой пояс\n4) Включите публикацию\n5) Запустите Превью",
        "rss_primary_next_feed": "👉 Самый важный шаг сейчас: добавьте первую ленту. Остальные настройки можно сделать позже.",
        "rss_primary_next_prompt": "👉 Отлично, источник подключён. Следующий шаг: задайте или проверьте промпт/стиль.",
        "rss_primary_next_schedule": "👉 Дальше откройте Расписание: выберите режим публикации и проверьте часовой пояс.",
        "rss_primary_next_enable": "👉 Почти готово. Когда всё проверите — включите публикацию.",
        "rss_primary_next_preview": "✅ Бот настроен. Используйте Превью для проверки и при необходимости смотрите Статус.",
        "rss_quickstart_title": "🚀 Быстрый старт RSS",
        "rss_quickstart_intro": "Короткий пошаговый путь для старта. К расширенным настройкам можно вернуться в любой момент.",
        "rss_quickstart_next_hint": "Нажмите следующий незавершённый шаг ниже.",
        "quickstart_step_channel": "Выберите канал для настройки",
        "quickstart_step_feed": "Добавьте первую ленту",
        "quickstart_step_prompt": "Задайте или проверьте промпт/стиль",
        "quickstart_step_mode": "Выберите простой режим публикации (рекомендуется)",
        "quickstart_step_timezone": "Проверьте часовой пояс",
        "quickstart_step_enable": "Включите публикацию",
        "quickstart_step_preview": "Запустите превью или проверьте LIVE-статус",
        "quickstart_simple_mode_set": "✅ Простой режим установлен: По интервалу. Дальше: проверьте часовой пояс и включите публикацию.",
        "schedule_mode_title_rss": "📰 Планировщик RSS + AI",
        "schedule_mode_title_creative": "✨ Планировщик Creative",
        "schedule_guided_intro":
            "Настройте по шагам:\n"
            "1) Выберите режим публикации\n"
            "2) Задайте слоты (Изменить расписание) или интервал\n"
            "3) При необходимости добавьте заблокированные часы\n"
            "4) Установите порог свежести\n"
            "5) Проверьте часовой пояс\n"
            "6) Включите публикацию\n\n"
            "Подсказки:\n"
            "• Интервал лучше для активных лент.\n"
            "• По времени лучше для фиксированных окон публикаций.\n"
            "• Слишком много ограничений может задерживать полезные посты.",
        "schedule_current": "Текущее расписание:\n{schedule}",
        "schedule_input_instructions": "Отправьте время публикаций в формате 24ч через запятую.\nПримеры:\n09:00\n09:00, 15:00, 21:30\n\nОтправьте \"clear\", чтобы удалить все слоты.",
        "schedule_invalid": "❌ Неверный формат. Используйте HH:MM или HH:MM, HH:MM",
        "schedule_saved": "✅ Расписание сохранено.",
        "schedule_cleared": "✅ Расписание очищено.",
        "schedule_enabled": "✅ Публикация теперь LIVE.",
        "schedule_disabled": "⏸ Публикация теперь ВЫКЛ.",
        "schedule_posting_mode": "Режим публикации: {mode}",
        "posting_mode_scheduled": "По времени",
        "posting_mode_interval": "По интервалу",
        "posting_mode_scheduled_set": "✅ Режим публикации: по времени.",
        "posting_mode_interval_set": "✅ Режим публикации: по интервалу.",
        "schedule_interval_current": "Интервал проверки: каждые {interval} мин",
        "schedule_freshness_current": "Свежесть постов: {minutes} мин",
        "schedule_empty_slots": "(не задано)",
        "schedule_not_set": "не задан",
        "schedule_blocked_hours_off": "ВЫКЛ",
        "schedule_status_on": "LIVE",
        "schedule_status_off": "ВЫКЛ",
        "schedule_times_empty": "(пусто)",
        "schedule_summary_channel": "• Канал: {channel}",
        "schedule_summary_mode": "• Режим публикации: {mode}",
        "schedule_summary_slots": "• Расписание / интервал: {slots}",
        "schedule_summary_timezone": "• Часовой пояс: {timezone}",
        "schedule_summary_blocked": "• Заблокированные часы: {blocked}",
        "schedule_summary_freshness": "• Порог свежести: {minutes} мин",
        "schedule_summary_status": "• LIVE-состояние: {status}",
        "schedule_summary_next_run": "• Следующий запуск: {next_run}",
        "schedule_summary_title": "Текущая конфигурация:",
        "activation_blocked_intro": "Нельзя включить публикацию, пока не исправлены пункты:",
        "activation_issue_channel": "Не выбран канал. Сначала подключите канал.",
        "activation_issue_feeds": "Не добавлены RSS-ленты. Добавьте минимум одну.",
        "activation_issue_timezone": "Не задан часовой пояс. Откройте Расписание → Часовой пояс.",
        "activation_issue_posting_mode": "Не настроен режим публикации. Выберите Интервал или Слоты.",
        "activation_issue_slots": "Для режима По времени не задано ни одного валидного слота.",
        "activation_warning_intro": "⚠️ Такая конфигурация может дать очень мало публикаций или ноль:",
        "activation_warn_blocked_hours": "Заблокированные часы покрывают около {hours} ч/сутки, поэтому проверки часто пропускаются.",
        "activation_warn_freshness": "Свежесть {minutes} мин — большинство записей может отсеиваться.",
        "activation_warn_interval": "Интервал {interval} мин — проверки происходят редко.",
        "activation_warn_slots_count": "Указан только один слот, окно публикации очень узкое.",
        "activation_warn_slots_gap": "Есть большие разрывы между слотами (до {hours} ч).",
        "activation_warn_low_volume_interval": "Оценка возможных проверок в день: {count}.",
        "activation_off_confirmed": "🛑 Автопост ВЫКЛ.",
        "live_title": "✅ Автопост LIVE",
        "live_line_channel": "Канал: {channel}",
        "live_line_mode": "Режим: {mode}",
        "live_line_schedule": "Публикация: {schedule}",
        "live_line_interval": "каждые {interval} мин",
        "live_line_timezone": "Часовой пояс: {timezone}",
        "live_line_freshness": "Свежесть: {minutes} мин",
        "live_line_blocked": "Заблокированные часы: {blocked}",
        "live_line_next_check": "Следующая проверка: {next_run}",
        "live_line_next_post_hint": "Следующий возможный пост: зависит от наличия новых записей.",
        "status_live_title": "📡 LIVE-состояние автопоста",
        "status_live_mode_section": "Режим: {mode}",
        "preview_no_feeds": "Нет RSS-лент. Сначала добавьте: /addfeed <url>",
        "preview_no_items_warning": "⚠️ Новых непоказанных записей не найдено.\nЭто нормально, если:\n- лента уже была обработана\n- новых публикаций пока нет\n\nПопробуйте позже или добавьте ещё одну ленту.",
        "preview_empty_no_feed": "Для этого канала пока нет подключённых лент.\n\nСледующий шаг:\n• добавьте первую ленту\n• затем снова запустите Превью",
        "preview_empty_feed_no_items": "Лента подключена, но сейчас в ней нет читаемых записей.\n\nСледующий шаг:\n• попробуйте другой источник\n• или проверьте позже",
        "preview_empty_all_processed": "Сейчас нет непоказанных записей — это часто нормально.\nЛента могла уже обработаться, либо новых публикаций пока нет.\n\nСледующий шаг:\n• попробуйте позже\n• или добавьте ещё одну ленту",
        "preview_empty_filtered": "Записи найдены, но ни одна не прошла текущие фильтры свежести/релевантности.\n\nСледующий шаг:\n• проверьте, есть ли в ленте свежие посты\n• увеличьте окно свежести или попробуйте другой источник",
        "preview_fallback_text_only": "Не удалось собрать изображение, поэтому ниже показан текстовый превью-вариант.",
        "preview_temporarily_unavailable": "Сейчас не удалось создать превью для этой настройки.",
        "preview_stage_config_failed": "Не удалось получить данные канала или режима для превью.",
        "preview_stage_rss_failed": "Не удалось получить RSS-запись для превью.",
        "preview_stage_ai_failed": "Не удалось сгенерировать текст для превью. Проверьте AI-модель и API-ключ.",
        "preview_stage_image_failed": "Не удалось собрать изображение для превью.",
        "preview_stage_send_failed": "Не удалось отправить превью в Telegram.",
        "preview_loading": "Готовлю превью, это может занять несколько секунд.",
        "preview_status_template_build_failed_normal": "Не удалось собрать изображение по шаблону. Показываю обычное превью.",
        "preview_status_no_rss_image_text_only": "У RSS-записи нет доступного изображения. Показываю текстовый вариант.",
        "preview_status_asset_load_failed_normal": "Не удалось загрузить шаблон или водяной знак. Показываю обычное превью.",
        "feed_management_title": "🧾 Управление лентами:",
        "feed_management_help": "Подсказка: отправьте прямую RSS-ссылку или ссылку на профиль X/Twitter — бот создаст RSS автоматически.",
        "feed_limit_status": "Использовано лент: {count}/{limit}",
        "feed_name_prompt": "Отправьте короткое название для этой ленты или отправьте \"-\" чтобы пропустить.",
        "feed_processing": "⏳ Проверяю и подключаю ленту...",
        "feed_recovery_invalid": "Эта ссылка не похожа на корректную RSS-ленту.\n\nПопробуйте:\n• отправить прямую RSS/XML ссылку\n• или отправить ссылку на профиль X (пример: https://x.com/username)",
        "feed_recovery_x_transform_failed": "Сейчас не удалось преобразовать этот профиль X/Twitter в читаемую RSS-ленту.\n\nПопробуйте:\n• отправить другой профиль\n• или отправить прямую RSS-ссылку",
        "feed_recovery_x_status": "Похоже, это ссылка на отдельный пост/status.\n\nЧто попробовать:\n• отправьте ссылку на профиль\nПример: https://x.com/username",
        "feed_recovery_x_profile_invalid": "Не удалось распознать ссылку на профиль X/Twitter.\n\nЧто попробовать:\n• отправьте только URL профиля\nПример: https://x.com/username",
        "feed_recovery_empty": "Лента существует, но сейчас в ней нет читаемых записей.\n\nПопробуйте:\n• выбрать другой источник\n• или проверить позже",
        "feed_recovery_unreachable": "Сейчас не удалось получить доступ к этой ленте.\n\nПопробуйте:\n• открыть ссылку в браузере и проверить доступность\n• повторить через несколько минут",
        "feed_recovery_unsupported": "Страница доступна, но возвращает неподдерживаемый формат (не RSS/Atom).\n\nЧто попробовать:\n• отправьте прямую RSS/XML ссылку\n• или выберите другой источник",
        "rss_first_success_feed": "✅ Первый источник подключён.\nДальше: задайте стиль/промпт, затем выберите расписание и часовой пояс.\nПеред запуском сделайте Превью.",
        "btn_lang": "🌐 Язык",
        "choose_lang": "Выберите язык:",
        "btn_setup": "🛠 Настройка",
        "btn_help": "❓ Помощь",
        "help_link": "https://telegra.ph/Instrukciya-po-polzovaniyu-botom-i-poleznye-materialy-02-27",
        "help_open_link": "Откройте эту ссылку:",
        "help_contact": "Если что-то непонятно, напишите мне.",
        "btn_status": "ℹ️ Статус",
        "btn_channel_management": "📺 Управление каналом",
        "btn_add_channel": "➕ Добавить канал",
        "btn_delete_channel": "🗑 Удалить канал",
        "btn_setchannel": "📌 Канал",
        "btn_unsetchannel": "🧹 Отключить канал",
        "btn_addfeed": "🧾 Лента (RSS)",
        "btn_deletefeed": "🗑 Удалить ленту",
        "btn_add_feed": "➕ Добавить ленту",
        "btn_delete_feed": "🗑 Удалить ленту",
        "btn_edit_prompt": "✍️ Задать стиль",
        "btn_channel_intake": "🧭 Понять канал",
        "btn_channel_intake_fast_start": "⚡ Быстрый старт",
        "btn_channel_intake_start": "🚀 Пройти настройку",
        "btn_channel_intake_view": "📋 Показать контекст",
        "btn_campaigns": "📈 Кампании",
        "btn_campaign_create": "➕ Создать кампанию",
        "btn_campaign_view": "📋 Показать кампании",
        "btn_campaign_activate": "🎯 Сделать активной",
        "btn_creative_publish_settings": "⚙️ Настройка публикаций",
        "btn_build_prompt_ai": "🪄 Конструктор промпта",
        "btn_copy_my_style": "🎭 Скопировать стиль",
        "btn_content_plan": "🗂 Контент-план",
        "btn_source_center": "🧠 Центр источников",
        "btn_topic_pillars": "🧱 Рубрики (главные темы)",
        "btn_idea_bank": "💡 Банк идей (быстрые идеи)",
        "btn_inspiration_links": "🔗 Вдохновляющие ссылки",
        "btn_source_snippets": "📝 Сниппеты (заметки/цитаты)",
        "btn_view_items": "📋 Показать",
        "btn_add_item": "➕ Добавить",
        "btn_idea_generate": "🪄 Сгенерировать идеи",
        "btn_delete_item": "🗑 Удалить",
        "btn_content_plan_generate": "🗓 Сгенерировать план на 7 дней",
        "btn_content_plan_view": "📋 Показать план",
        "btn_content_plan_regenerate_item": "🔄 Перегенерировать пункт",
        "btn_content_plan_edit_item": "✍️ Редактировать пункт",
        "btn_preview": "🧪 Превью",
        "btn_pause_posting": "⏸ Пауза публикаций",
        "btn_resume_posting": "▶️ Возобновить публикации",
        "btn_content_variety": "🎛 Разнообразие контента",
        "btn_visual_support": "🖼 Визуальная поддержка",
        "btn_visual_generate_idea": "🧩 Сгенерировать визуальную идею",
        "btn_visual_generate_search_query": "🔎 Сгенерировать поисковый запрос",
        "btn_visual_generate_ai_prompt": "🎨 Сгенерировать AI-промпт для изображения",
        "btn_variation_level": "Уровень вариативности",
        "btn_post_types": "Типы постов",
        "btn_avoid_repetition_on": "♻️ Избегать повторов: ВКЛ",
        "btn_avoid_repetition_off": "♻️ Избегать повторов: ВЫКЛ",
        "btn_edit_feeds": "🧾 Настройка лент",
        "btn_rss_quickstart": "🚀 Быстрый старт",
        "btn_quickstart_add_feed": "1) Добавить ленту",
        "btn_quickstart_set_prompt": "2) Задать стиль",
        "btn_quickstart_simple_mode": "3) Простой режим",
        "btn_quickstart_timezone": "4) Часовой пояс",
        "btn_quickstart_enable": "5) Включить публикацию",
        "btn_quickstart_preview": "6) Превью / статус",
        "btn_rss_output_settings": "🧩 Формат поста",
        "btn_post_format": "🧩 Формат поста",
        "rss_output_settings_title": "🧩 Настройки формата поста (RSS + AI):",
        "creative_output_settings_title": "🧩 Настройки формата поста (Creative):",
        "post_format_assets_info": "Визуальные элементы:\n• Шаблон: {template}\n• Водяной знак: {watermark}\n• Жирный заголовок: {bold_title}\n• Кастомные эмодзи: {emoji}\n\nШаблон = фон/заготовка для оформления изображений.\nВодяной знак = логотип или отметка канала поверх изображения.\nРекомендуется: шаблон JPG/PNG, водяной знак PNG (лучше с прозрачностью).\nАвтокомпоновка используется, когда в RSS-записи есть изображение.",
        "status_added": "добавлен",
        "status_not_added": "не добавлен",
        "btn_edit_template_image": "🖼 Шаблон",
        "btn_edit_watermark": "🏷 Водяной знак",
        "btn_add_asset": "➕ Добавить",
        "btn_replace_asset": "♻️ Заменить",
        "btn_delete_asset": "🗑 Удалить",
        "asset_manage_template_title": "🖼 Управление шаблоном",
        "asset_manage_watermark_title": "🏷 Управление водяным знаком",
        "asset_manage_template_help": "Здесь можно управлять изображением шаблона.",
        "asset_manage_watermark_help": "Здесь можно управлять водяным знаком.",
        "asset_manage_status": "Текущий статус: {status}",
        "asset_prompt_send_template": "Отправьте одно изображение для шаблона/фона (как фото или документ-изображение).\nДля лучшего результата используйте широкое качественное изображение.",
        "asset_prompt_send_watermark": "Отправьте одно изображение для водяного знака/логотипа (как фото или документ-изображение).\n\nПодсказка: если нужно, фон можно удалить здесь: https://www.remove.bg/\nЛучше загружать PNG, желательно как файл (документ). Небольшая прозрачность обычно выглядит лучше.",
        "asset_saved_template": "✅ Шаблон сохранён.",
        "asset_saved_watermark": "✅ Водяной знак сохранён.",
        "asset_deleted_template": "✅ Шаблон удалён.",
        "asset_deleted_watermark": "✅ Водяной знак удалён.",
        "asset_upload_invalid": "Пожалуйста, отправьте изображение как фото или документ-изображение.",
        "asset_upload_error": "❌ Не удалось сохранить изображение. Попробуйте ещё раз.",
        "btn_source_link_on": "🔗 Ссылка на источник: ВКЛ",
        "btn_source_link_off": "🔗 Ссылка на источник: ВЫКЛ",
        "btn_feed_image_on": "🖼 Картинка из ленты: ВКЛ",
        "btn_feed_image_off": "🖼 Картинка из ленты: ВЫКЛ",
        "btn_rss_cta_on": "📣 CTA: ВКЛ",
        "btn_rss_cta_off": "📣 CTA: ВЫКЛ",
        "btn_bold_title_on": "🅱️ Жирный заголовок: ВКЛ",
        "btn_bold_title_off": "🅱️ Жирный заголовок: ВЫКЛ",
        "btn_emoji_management": "✨ Управление эмодзи",
        "btn_add_emoji": "✨ Добавить эмодзи",
        "btn_add_update_emoji": "✨ Добавить / обновить",
        "btn_delete_emoji": "🗑 Удалить эмодзи",
        "emoji_management_title": "✨ Управление эмодзи",
        "emoji_management_status": "Эмодзи сохранены: {emoji}\nСсылка сохранена: {link}",
        "status_yes": "да",
        "status_no": "нет",
        "emoji_prompt_send": "Можно отправить ссылку на набор эмодзи или просто прислать сами эмодзи сообщением (включая premium/custom). Ссылка сохраняется как справка.",
        "emoji_saved": "✅ Стиль эмодзи сохранён.",
        "emoji_deleted": "✅ Стиль эмодзи удалён.",
        "channel_saved_named": "✅ Канал подключён: {channel}",
        "channel_forward_invalid": "Не удалось определить канал из этого сообщения. Перешлите пост из вашего канала после добавления бота в админы.",
        "channel_forward_admin_missing": "Канал найден, но бот не администратор. Дайте права администратора и перешлите пост ещё раз.",
        "channel_forward_access_error": "Канал найден, но не удалось проверить доступ. Убедитесь, что бот админ канала, и перешлите пост снова.",
        "rss_cta_prompt": "Отправьте CTA-текст одним сообщением. Он будет добавляться к каждому RSS-посту, когда CTA включён.",
        "rss_cta_saved": "✅ CTA-текст сохранён.",
        "rss_posting_paused_short": "RSS на паузе",
        "rss_posting_resumed_short": "RSS возобновлён",
        "rss_posting_paused_notice": "⏸ Пауза временно останавливает автопостинг RSS.",
        "rss_posting_resumed_notice": "▶️ После возобновления бот заново оценивает RSS-кандидаты и не публикует устаревшие пропущенные посты автоматически.",
        "btn_schedule_rss": "📰 Расписание RSS + AI",
        "btn_schedule_creative": "✨ Расписание Creative",
        "btn_schedule_edit": "✍️ Изменить расписание",
        "btn_schedule_edit_interval": "⏱ Изменить интервал",
        "btn_schedule_quiet_hours": "🌙 Заблокированные часы",
        "btn_schedule_freshness": "🕰 Свежесть постов",
        "btn_quiet_hours_add": "➕ Добавить тихие часы",
        "btn_quiet_hours_delete": "🗑 Удалить тихие часы",
        "btn_posting_mode_scheduled": "🔁 Режим: По времени",
        "btn_posting_mode_interval": "🔁 Режим: По интервалу",
        "btn_schedule_toggle_on": "✅ Включить",
        "btn_schedule_toggle_off": "⏸ Выключить",
        "interval_input_instructions": "Отправьте интервал в минутах (только число).\nПримеры: 60, 120, 180\n\nНапишите \"cancel\" для возврата.",
        "interval_invalid": "❌ Неверный интервал. Отправьте целое число в минутах (например: 60).",
        "interval_saved": "✅ Интервал сохранён: каждые {interval} мин.",
        "quiet_hours_management_title": "🌙 Заблокированные часы",
        "quiet_hours_list_title": "Сохранённые заблокированные окна:",
        "quiet_hours_empty": "Заблокированные окна пока не добавлены.",
        "quiet_hours_input_instructions": "Отправьте время без публикаций в 24-часовом формате:\nHH:MM-HH:MM\nПримеры:\n- 12:00-13:00\n- 23:30-08:00\nДиапазоны через полночь поддерживаются.\nОтправьте \"cancel\", чтобы вернуться.",
        "quiet_hours_invalid": "❌ Неверный формат. Используйте HH:MM-HH:MM (например: 12:00-13:00 или 23:30-08:00).",
        "quiet_hours_saved": "✅ Заблокированное окно добавлено: {start}-{end}",
        "quiet_hours_deleted": "✅ Заблокированное окно удалено: {window}",
        "quiet_hours_delete_empty": "Нет заблокированных окон для удаления.",
        "schedule_timezone": "Часовой пояс: {timezone}",
        "btn_schedule_timezone": "🌐 Часовой пояс",
        "timezone_input_instructions": "Укажите часовой пояс для выбранного канала.\nИспользуйте UTC+2, UTC-5, +3, -4 или 0.\nОтправьте \"cancel\", чтобы вернуться.",
        "timezone_autodetected_notice": "✅ Часовой пояс канала автоматически установлен: {timezone} (унаследован из прежних настроек).",
        "timezone_fallback_notice": "ℹ️ Надёжно определить часовой пояс не удалось, поэтому сохранён резервный вариант {timezone}. Вы можете изменить его позже.",
        "freshness_input_instructions": "Отправьте порог свежести в минутах (15..1440).\nБолее старые материалы будут пропускаться.\nОтправьте \"cancel\", чтобы вернуться.",
        "freshness_invalid": "❌ Некорректное значение свежести. Введите целое число от 15 до 1440.",
        "freshness_saved": "✅ Порог свежести сохранён: {minutes} мин.",
        "timezone_invalid": "❌ Неверный часовой пояс. Используйте UTC+0, UTC+2, UTC-5, +3, -4 или 0.",
        "timezone_saved": "✅ Часовой пояс сохранён: {timezone}",
        "variation_level_title": "🎚 Вариативность. Выберите уровень:",
        "variation_level_value_low": "Низкий",
        "variation_level_value_balanced": "Сбалансированный",
        "variation_level_value_high": "Высокий",
        "post_types_title": "🧩 Типы постов. Включите один или несколько:",
        "post_type_educational": "Обучающий",
        "post_type_opinion": "Мнение",
        "post_type_story": "История",
        "post_type_checklist": "Чек-лист",
        "post_type_question": "Вопрос",
        "post_type_myth_vs_fact": "Миф vs Факт",
        "post_type_mini_case": "Мини-кейс",
        "creative_variety_title": "🎛 Разнообразие контента",
        "creative_variety_intro": "Здесь можно сделать посты более однотипными или более разнообразными.\nИспользуйте это, если хотите больше форматов и углов подачи.",
        "creative_variety_note": "Настройки мягко добавляют вариативность, но главный приоритет у вашего Creative-промпта.",
        "creative_publish_settings_title": "⚙️ Настройка публикаций (Creative)",
        "channel_intake_title": "🧭 Понять канал",
        "channel_intake_intro": "Расскажите о канале структурно. Этот контекст станет основой для идей, кампаний и генерации постов.",
        "channel_intake_start": "Отвечайте коротко и конкретно. Обычно достаточно 1–3 предложений.\nВ любой момент отправьте \"cancel\".",
        "channel_intake_empty": "Контекст канала пока не заполнен. Запустите настройку.",
        "channel_intake_saved": "✅ Контекст канала сохранён.",
        "channel_intake_cancelled": "Настройка канала отменена.",
        "channel_intake_q_channel_about": "О чём ваш канал?\nЗачем: это задаёт основной вектор контента.\nХороший ответ: ниша + кому полезно + обещание, 1–3 предложения.\nПример: «Канал для начинающих экспертов. Даю практику по контенту и продажам через Telegram».",
        "channel_intake_q_audience": "Кто ваша аудитория?\nЗачем: чем точнее портрет, тем точнее посты.\nХороший ответ: роль, уровень и контекст.\nПример: «Эксперты 23–40, уже ведут канал, но нестабильно публикуются».",
        "channel_intake_q_audience_wants": "Что аудитория сильнее всего хочет сейчас?\nЗачем: это помогает выбрать приоритетные темы.\nХороший ответ: 1–3 желаемых результата.\nПример: «Получать лиды из канала и не выгорать от ежедневного контента».",
        "channel_intake_q_audience_pains": "Какие боли/проблемы мешают им?\nЗачем: сильный контент закрывает конкретные барьеры.\nХороший ответ: реальные препятствия и страхи.\nПример: «Нет понятного оффера, низкий отклик, страх продавать в лоб».",
        "channel_intake_q_tone_style": "Какой тон/стиль нужен постам?\nЗачем: это удерживает единый голос канала.\nХороший ответ: 2–4 характеристики и что избегать.\nПример: «Дружелюбно и по делу, без инфоцыганства и агрессии».",
        "channel_intake_q_offers": "Что вы продаёте/продвигаете?\nЗачем: контент должен вести к вашим предложениям.\nХороший ответ: продукт/услуга + формат + при желании цена.\nПример: «Личные консультации, групповая программа на 4 недели, мини-курс за 4900 ₽».",
        "channel_intake_q_creator_goals": "Какие цели по контенту на ближайшие недели?\nЗачем: это задаёт фокус кампаний и CTA.\nХороший ответ: 1–2 измеримые цели.\nПример: «Собрать 15 заявок на консультацию за 3 недели».",
        "channel_intake_q_good_posts": "Какие хорошие посты хотите чаще?\nЗачем: примеры помогают повторять сильные паттерны.\nХороший ответ: 1–3 примера и почему сработали.\nПример: «Кейсы с цифрами и выводом — дают много сохранений и заявок».",
        "channel_intake_q_bad_posts": "Какие посты не хотите повторять?\nЗачем: это снижает риск слабых генераций.\nХороший ответ: 1–3 примера и что не понравилось.\nПример: «Общие мотивационные тексты — просмотры есть, заявок нет».",
        "channel_intake_q_never_sound_like": "Как канал никогда не должен звучать?\nЗачем: это защищает доверие к бренду.\nХороший ответ: запретные формулировки и тон.\nПример: «Без манипуляций, без высокомерия, без фальшивой срочности».",
        "channel_intake_label_channel_about": "Канал",
        "channel_intake_label_audience": "Аудитория",
        "channel_intake_label_audience_wants": "Что хочет аудитория",
        "channel_intake_label_audience_pains": "Боли аудитории",
        "channel_intake_label_tone_style": "Тон/стиль",
        "channel_intake_label_offers": "Офферы",
        "channel_intake_label_creator_goals": "Цели",
        "channel_intake_label_good_posts": "Хорошие примеры",
        "channel_intake_label_bad_posts": "Плохие примеры",
        "channel_intake_label_never_sound_like": "Никогда не звучать как",
        "idea_bank_generating": "⏳ Генерирую идеи на основе контекста канала...",
        "idea_bank_generated": "✅ Добавлено идей: {count}.",
        "campaigns_intro": "Собирайте кампании с понятной целью и последовательностью контента по дням.",
        "campaign_create_start": "Создаём кампанию.\nОтвечайте по шагам. Для отмены отправьте \"cancel\".",
        "campaign_create_saved": "✅ Кампания создана и назначена активной.",
        "campaign_create_cancelled": "Создание кампании отменено.",
        "campaign_empty": "Кампаний пока нет. Создайте первую.",
        "campaign_list_title": "📈 Сохранённые кампании:",
        "campaign_activate_prompt": "Отправьте номер кампании для активации:",
        "campaign_activate_invalid": "Не нашёл кампанию с таким номером.",
        "campaign_activate_saved": "✅ Активная кампания обновлена.",
        "campaign_active_label": "🎯 Активная кампания: {name}",
        "campaign_q_goal": "Какая цель кампании?\nПочему важно: цель определяет всю цепочку.\nХороший ответ: один конкретный бизнес-результат.\nПример: «Получить 20 заявок на созвон за 10 дней».",
        "campaign_q_offer": "Что конкретно продаёте/продвигаете?\nПочему важно: без ясного оффера сложно строить сообщения.\nХороший ответ: что это, для кого и в каком формате.\nПример: «4-недельная программа по запуску продаж через Telegram».",
        "campaign_q_duration": "Сколько дней длится кампания?\nПочему важно: от этого зависит темп прогрева.\nХороший ответ: одно число (3, 5, 7, 14...).\nПример: «7».",
        "campaign_q_target_action": "Какое точное действие должен сделать человек?\nПочему важно: каждый пост должен вести к этому шагу.\nХороший ответ: одно наблюдаемое действие.\nПример: «Написать в ЛС слово START для деталей».",
        "campaign_q_awareness": "Какой сейчас уровень осознанности/ситуации аудитории?\nПочему важно: понять, сначала объяснять или сразу продавать.\nХороший ответ: что люди уже понимают и где застряли.\nПример: «Понимают, что нужен контент, но не верят, что смогут вести канал стабильно».",
        "campaign_q_objections": "Какие ключевые возражения нужно закрыть?\nПочему важно: возражения блокируют конверсию.\nХороший ответ: 2–5 реальных сомнений.\nПример: «Дорого, нет времени, не уверены, что сработает в их нише».",
        "campaign_q_benefits": "Какие ключевые выгоды подчеркнуть?\nПочему важно: выгоды формируют ценность каждого этапа.\nХороший ответ: 2–5 практических результатов.\nПример: «Понятная система контента, быстрее писать посты, больше входящих заявок».",
        "campaign_q_urgency": "Есть ли срочность / запуск / событие?\nПочему важно: помогает выбрать силу CTA.\nХороший ответ: дедлайн, окно или повод действовать сейчас.\nПример: «Набор закрывается в пятницу в 21:00 по МСК».",
        "quickstart_start": "⚡ Быстрый старт (около 2 минут).\nОтветим на 4 главных вопроса и сразу получим первый стратегический превью-пост.",
        "quickstart_cancelled": "Быстрый старт отменён.",
        "quickstart_q_channel_about": "О чём ваш канал?\n1–2 конкретных предложения.\nПример: «Практический контент-маркетинг для экспертов в Telegram».",
        "quickstart_q_audience": "Кто ваша аудитория?\nЧем конкретнее, тем лучше.\nПример: «Коучи и консультанты с маленькими Telegram-каналами».",
        "quickstart_q_offer": "Что вы продаёте/продвигаете?\nПример: «Личные стратегические сессии и групповая программа на 4 недели».",
        "quickstart_q_goal": "Какая у вас текущая цель?\nПример: «Получить 8 созвонов в этом месяце».",
        "quickstart_saved": "✅ Быстрая настройка сохранена. Теперь у канала достаточно контекста для более точной генерации.",
        "quickstart_why_post": "Почему выбран такой первый пост: он быстро попадает в боль аудитории, подводит к офферу и даёт понятный следующий шаг.",
        "quickstart_preview_title": "🧪 Стратегический превью-пост:",
        "quickstart_preview_failed": "⚠️ Сейчас не удалось сгенерировать превью, но быстрый профиль сохранён. Нажмите «Превью», чтобы повторить.",
        "first_success_next_step_quickstart": "Следующий лучший шаг: добавьте боли и возражения в полной настройке, затем сделайте ещё одно превью или соберите кампанию.",
        "first_success_next_step_campaign": "Теперь у канала достаточно контекста для более сильной генерации. Дальше можно усилить результат, добавив больше болей и возражений аудитории.",
        "campaign_created_for_goal": "Цель кампании: {goal}",
        "campaign_fallback_goal": "Кампания",
        "campaign_arc_title": "🗺 Последовательность кампании:",
        "campaign_arc_empty": "Кампания сохранена, но детальная последовательность по дням пока недоступна.",
        "campaign_arc_default_stage": "Этап",
        "campaign_arc_default_direction": "Направление",
        "campaign_arc_default_hook": "Практичный угол входа",
        "campaign_arc_cta_optional": "Мягкий CTA / шаг к конверсии",
        "campaign_arc_day_block": "День {day}\n• Цель этапа: {stage}\n• Рекомендуемый угол: {hook}\n• Направление поста: {direction}\n• CTA / роль в конверсии: {cta}",
        "creative_variety_summary": "Уровень: {level}\nТипы постов: {post_types}\nИзбегать повторов: {avoid}",
        "creative_visual_support_title": "🖼 Визуальная поддержка",
        "creative_visual_support_intro": "Получайте идеи для визуала, поисковые фразы и AI-промпты для изображений.\nИспользуйте это, если хотите подбирать картинки под посты.",
        "creative_visual_generating_idea": "Генерирую визуальную идею...",
        "creative_visual_generating_search_query": "Генерирую поисковый запрос...",
        "creative_visual_generating_ai_prompt": "Генерирую AI-промпт для изображения...",
        "creative_visual_topic_fallback": "Текущая тема из контент-плана не найдена. Использую сохранённый Creative-промпт.",
        "creative_visual_label_idea": "🧩 Визуальная идея",
        "creative_visual_label_search_query": "🔎 Поисковый запрос",
        "creative_visual_label_ai_prompt": "🎨 AI-промпт для изображения",
        "creative_visual_error": "❌ Сейчас не удалось сгенерировать визуальную подсказку. Попробуйте ещё раз.",
        "content_plan_title": "🗂 Контент-план",
        "content_plan_intro": "Планируйте посты на несколько дней вперёд.\nЭто удобно, если хотите более понятную структуру недели.",
        "content_plan_generating": "⏳ Генерирую план на 7 дней...",
        "content_plan_generated": "✅ План на 7 дней сохранён.",
        "content_plan_current_title": "📋 Текущий недельный план:",
        "content_plan_empty": "План пока пуст. Нажмите «Сгенерировать план на 7 дней».",
        "content_plan_no_plan": "Для этого канала пока нет сохранённого плана.",
        "content_plan_choose_regenerate": "Выберите пункт для перегенерации:",
        "content_plan_choose_edit": "Выберите пункт для редактирования:",
        "content_plan_regenerating_item": "⏳ Перегенерирую выбранный пункт...",
        "content_plan_item_regenerated": "✅ Пункт перегенерирован.",
        "content_plan_edit_prompt": "Отправьте новый текст темы для {day_label}.\nТекущая тема: {topic}\nТекущий угол: {angle}\n\nОтправьте \"cancel\", чтобы отменить.",
        "content_plan_edit_cancelled": "Редактирование отменено.",
        "content_plan_item_saved": "✅ Пункт плана обновлён.",
        "content_plan_item_line": "{idx}) {day_label}\nТема: {topic}\nУгол: {angle}\nТип: {post_type}\nЦель: {goal}\nСтатус: {status}",
        "source_center_title": "🧠 Центр источников",
        "source_center_intro": "Добавьте материалы, чтобы бот писал точнее и сильнее.\n• Рубрики = главные темы канала\n• Банк идей = быстрые идеи для постов\n• Вдохновляющие ссылки = полезные примеры\n• Сниппеты = заметки, цитаты или вставки текста",
        "source_delete_choose": "Выберите элемент для удаления:",
        "source_delete_empty": "Список пуст. Сначала добавьте элемент.",
        "source_add_cancelled": "Добавление отменено.",
        "source_item_deleted": "✅ Удалено: {item}",
        "source_topic_pillars_title": "🧱 Рубрики (главные темы)",
        "source_topic_pillars_empty": "Рубрики пока не добавлены.",
        "source_topic_pillars_add_prompt": "Отправьте одну рубрику.\n\nПримеры:\n• личное мнение\n• образовательные советы\n• закулисье\n\nОтправьте \"cancel\" для отмены.",
        "source_topic_pillars_saved": "✅ Рубрика сохранена.",
        "source_idea_bank_title": "💡 Банк идей (быстрые идеи)",
        "source_idea_bank_empty": "В банке идей пока пусто.",
        "source_idea_bank_add_prompt": "Отправьте одну идею.\n\nПримеры:\n• Почему авторы выгорают из-за копирования трендов\n• Маленькие каналы выигрывают за счёт сильного мнения\n\nОтправьте \"cancel\" для отмены.",
        "source_idea_bank_saved": "✅ Идея сохранена.",
        "source_inspiration_links_title": "🔗 Вдохновляющие ссылки",
        "source_inspiration_links_empty": "Ссылки пока не добавлены.",
        "source_inspiration_links_add_prompt": "Отправьте одну ссылку для вдохновения.\n\nОтправьте \"cancel\" для отмены.",
        "source_inspiration_links_saved": "✅ Ссылка сохранена.",
        "source_source_snippets_title": "📝 Сниппеты (заметки/цитаты)",
        "source_source_snippets_empty": "Сниппеты пока не добавлены.",
        "source_source_snippets_add_prompt": "Отправьте один текстовый сниппет/заметку.\n\nОтправьте \"cancel\" для отмены.",
        "source_source_snippets_saved": "✅ Сниппет сохранён.",
        "label_on": "ВКЛ",
        "label_off": "ВЫКЛ",
        "status_id": "ID",
        "status_channels": "Каналы",
        "status_rss_daily": "Доступно RSS постов/день",
        "status_creative_monthly_pool": "Creative-пул на месяц",
        "status_creative_monthly_used": "Creative использовано в этом месяце",
        "status_creative_monthly_remaining": "Creative осталось в этом месяце",
        "status_creative_monthly_period": "Период Creative-пула",
        "status_valid_until": "Подписка активна до",
        "posting_limit_reached": "Лимит постов за текущий период исчерпан.",
        "creative_quota_title": "📦 Creative квота на месяц",
        "creative_quota_pool": "• Пул на месяц: {pool}",
        "creative_quota_used": "• Использовано в этом месяце: {used}",
        "creative_quota_remaining": "• Осталось в этом месяце: {remaining}",
        "creative_quota_period": "• Период сброса: {period} (ГГГГ-ММ)",
        "status_not_set": "не задано",
        "status_inactive": "не активна",
        "status_title": "📊 Статус аккаунта",
        "btn_setstyle": "✍️ Стиль",
        "btn_showstyle": "📄 Показать стиль",
        "btn_resetstyle": "♻️ Сбросить стиль",
        "btn_on": "🤖 Автопост ВКЛ",
        "btn_off": "🛑 ВЫКЛ",
        "modes_help": "Выберите режим командами:\n/mode rss\n/mode creator\n/mode both",
        "prompt_current": "Текущий промпт:\n{prompt}",
        "prompt_current_rss": "Текущий промпт RSS + AI:\n{prompt}",
        "prompt_current_creative": "Текущий промпт Creative:\n{prompt}",
        "prompt_empty": "Промпт пока не сохранён. Используется стиль по умолчанию.",
        "style_setup_title": "Задать стиль:",
        "style_setup_current_prefix": "Текущий текст промпта:\n{prompt}",
        "style_setup_empty": "Промпт пока не сохранён.",
        "style_setup_saved": "✅ Текущий промпт сохранён.",
        "prompt_edit_instructions": "Отправьте готовый промпт одним сообщением. Напишите \"cancel\", чтобы оставить текущий без изменений.",
        "prompt_edit_cancel_hint": "Напишите \"cancel\", чтобы оставить текущий промпт без изменений.",
        "prompt_guidance_creative": (
            "Как написать хороший Creative-промпт для Telegram:\n"
            "• Тема/ниша: о чём именно вы пишете.\n"
            "• Тон/голос: экспертный, дружелюбный, дерзкий и т.д.\n"
            "• Аудитория: для кого ваш канал.\n"
            "• Длина: типичный объём в строках/символах.\n"
            "• Структура: хук → основные мысли → вывод.\n"
            "• CTA: мягкий призыв, вопрос, переход в ЛС, ссылка и т.д.\n"
            "• Избегать: клише, кликбейта, запрещённых/нерелевантных тем.\n\n"
            "Шаблон (скопируйте и отредактируйте):\n"
            "Ты пишешь Telegram-посты для [ниша].\n"
            "Тон: [тон/голос]. Аудитория: [целевая аудитория].\n"
            "Объём каждого поста: [длина].\n"
            "Структура: 1) цепляющий хук, 2) 2–4 практичные мысли/примера, 3) короткий вывод, 4) CTA: [стиль CTA].\n"
            "Избегай: [что избегать]."
        ),
        "prompt_guidance_rss": (
            "Как написать хороший RSS + AI промпт для Telegram:\n"
            "• Преобразование контента: переписывай в вашем стиле, не копируй текст.\n"
            "• Тон/голос: деловой, нейтральный, энергичный и т.д.\n"
            "• Формат саммари: короткий дайджест или более подробное объяснение.\n"
            "• Длина: типичный объём в строках/символах.\n"
            "• Мнение: добавлять ваш комментарий или строго нейтрально.\n"
            "• Завершение/CTA: вопрос, подписка, репост, без призыва.\n"
            "• Избегать: выдуманных фактов, хайпа, повторов, слишком длинных вступлений.\n\n"
            "Шаблон (скопируйте и отредактируйте):\n"
            "Переписывай RSS/новости в Telegram-посты в тоне [тон].\n"
            "Формат: короткий хук + понятное саммари + ключевой вывод.\n"
            "Объём: [длина].\n"
            "Режим мнения: [нейтрально / добавить краткий комментарий].\n"
            "Завершение: [CTA или без CTA].\n"
            "Избегай: [что избегать]."
        ),
        "prompt_edit_cancelled": "Промпт не изменён.",
        "prompt_edit_saved": "✅ Промпт обновлён.",
        "prompt_builder_intro_creative": "🪄 AI-конструктор промпта (Creative)\n\nЯ задам несколько коротких вопросов и соберу готовый Creative-промпт.\n\nВ любой момент напишите \"cancel\" для выхода.",
        "prompt_builder_intro_rss": "🪄 AI-конструктор промпта (RSS + AI)\n\nЯ задам несколько коротких вопросов и соберу готовый RSS + AI промпт.\n\nВ любой момент напишите \"cancel\" для выхода.",
        "prompt_builder_q_creative_1": "1/7 Какая у вас ниша/тема?\n\nПримеры:\n• местные футбольные новости\n• обновления по киберспорту\n• питание для бегунов",
        "prompt_builder_q_creative_2": "2/7 Кто ваша целевая аудитория?\n\nПримеры:\n• футбольные фанаты\n• болельщики Барселоны\n• широкая спортивная аудитория\n• обычная Telegram-аудитория",
        "prompt_builder_q_creative_3": "3/7 Какой тон должен быть у постов?\n\nПримеры:\n• профессиональный новостной стиль\n• дружелюбный голос фаната\n• нейтрально-информативный\n• энергичный спортивный комментарий",
        "prompt_builder_q_creative_4": "4/7 Какие типы постов вам нужны чаще всего?\n\nПримеры:\n• короткие новостные выжимки\n• мнения\n• чеклисты\n• посты в формате вопрос-ответ",
        "prompt_builder_q_creative_5": "5/7 Какой примерно размер поста вы хотите?\n\nНапример:\n• короткий пост (2–3 предложения)\n• средний пост (4–6 предложений)\n• до ~100 слов",
        "prompt_builder_q_creative_6": "6/7 Чего нужно избегать?\n\nПримеры:\n• кликбейта\n• сленга\n• политических тем\n• агрессивной подачи",
        "prompt_builder_q_creative_7": "7/7 На каком языке должны быть посты? (English/Русский)",
        "prompt_builder_q_rss_1": "1/7 О чём лента/тематика?\n\nПримеры:\n• трансферы в футболе\n• турниры по киберспорту\n• новости о стартапах",
        "prompt_builder_q_rss_2": "2/7 Кто ваша целевая аудитория?\n\nПримеры:\n• футбольные фанаты\n• болельщики Барселоны\n• широкая спортивная аудитория\n• обычная Telegram-аудитория",
        "prompt_builder_q_rss_3": "3/7 Какой тон должен быть у постов?\n\nПримеры:\n• профессиональный новостной стиль\n• дружелюбный голос фаната\n• нейтрально-информативный\n• энергичный спортивный комментарий",
        "prompt_builder_q_rss_4": "4/7 Какой примерно размер поста вы хотите?\n\nНапример:\n• короткий пост (2–3 предложения)\n• средний пост (4–6 предложений)\n• до ~100 слов",
        "prompt_builder_q_rss_5": "5/7 Нейтральные саммари или более выразительный авторский угол?\n\nПримеры:\n• в основном нейтральная выжимка\n• короткий редакторский акцент",
        "prompt_builder_q_rss_6": "6/7 Чего нужно избегать?\n\nПримеры:\n• хайпа\n• повторов\n• слишком большого числа хештегов\n• длинных вступлений",
        "prompt_builder_q_rss_7": "7/7 На каком языке должны быть посты? (English/Русский)",
        "prompt_builder_generating": "⏳ Генерирую промпт...",
        "prompt_builder_review": "Вот сгенерированный промпт:\n\n{prompt}\n\nСохранить его для этого режима?",
        "prompt_builder_saved": "✅ Промпт сохранён для этого режима.",
        "prompt_builder_cancelled": "Конструктор промпта отменён. Изменения не сохранены.",
        "prompt_builder_error": "❌ Сейчас не удалось сгенерировать промпт. Попробуйте ещё раз.",
        "copy_style_intro": "Отправьте мне 3 поста из вашего канала.\nЯ проанализирую тон, подачу и структуру и создам промпт в вашем стиле.",
        "copy_style_progress": "Получил. Отправьте ещё {left} пост{suffix}.",
        "copy_style_invalid": "Пожалуйста, отправьте текстовые посты, чтобы я мог проанализировать стиль.",
        "copy_style_success": "✅ Готово. Промпт для этого режима обновлён по вашему стилю.",
        "copy_style_loading": "Готово. Подготавливаю промпт, это займёт несколько секунд.",
        "copy_style_review": "Промпт в вашем стиле готов.\n\n{prompt}\n\nПеред сохранением можно добавить детали: язык постов, размер, чего избегать, для какой аудитории писать, CTA/концовку и писать нейтрально или с комментариями.\nМожно сохранить его сразу или сначала отредактировать. Вы также можете скопировать весь промпт, поправить его и отправить обратно финальную версию.",
        "copy_style_edit_ready": "Ниже сгенерированный черновик. Отредактируйте его и отправьте финальную версию:\n\n{prompt}",
        "btn_save": "💾 Сохранить",
        "btn_edit": "✍️ Редактировать",
        "btn_regenerate": "🔄 Перегенерировать",
        "btn_cancel": "❌ Отмена",
        "feeds_empty": "Ленты пока не добавлены.",
        "feed_added": "✅ Лента добавлена.",
        "feed_deleted": "✅ Лента удалена.",
        "feed_duplicate": "Эта лента уже добавлена для этого канала.",
        "feed_read_failed": "Не удалось прочитать ленту. Отправьте корректную RSS/Atom ссылку.",
        "feed_auto_failed": "Не удалось автоматически создать RSS для этого профиля X/Twitter. Попробуйте другой профиль или отправьте прямую RSS-ссылку.",
        "feed_x_profile_only": "Отправьте ссылку на профиль X/Twitter (например, https://x.com/username), а не на отдельный пост.",
        "feed_limit_reached": "Для канала по умолчанию доступно до {limit} лент.\nЧтобы добавить больше, нужен дополнительный доступ к лентам.",
        "channel_deleted": "✅ Канал удалён.",
        "channel_empty": "Канал не настроен.",
        "channels_list_title": "Сохранённые каналы ({count}/{slots}):",
        "channels_empty_state": "Пока нет сохранённых каналов.\nДоступно слотов: {slots}.",
        "channel_choose_delete": "Выберите канал для удаления:",
        "channel_deleted_named": "✅ Канал удалён: {channel}",
        "channel_slots_limit": "Достигнут лимит каналов ({count}/{slots}). Увеличьте доступ, чтобы добавить ещё канал.",
        "channel_picker_title": "Выберите канал, чтобы продолжить:",
        "channel_picker_empty": "Каналы не найдены. Сначала добавьте канал в управлении каналами.",
        "channel_selected_now": "📌 Выбран канал: {channel}",
        "start_welcome": (
            "👋 Добро пожаловать в Postora.\n\n"
            "Я помогаю создавать и публиковать посты по расписанию для вашего Telegram-канала.\n\n"
            "Чтобы начать, откройте ⚙️ Настройку, выберите режим, подключите канал и задайте промпт, ленты и расписание.\n"
            "Тариф и оплату можно настроить отдельно в любое время."
        ),
        "start_welcome_named": (
            "👋 Привет, {name}!\n\n"
            "Я помогаю создавать и публиковать посты по расписанию для вашего Telegram-канала.\n\n"
            "Чтобы начать, откройте ⚙️ Настройку, выберите режим, подключите канал и задайте промпт, ленты и расписание.\n"
            "Тариф и оплату можно настроить отдельно в любое время."
        ),
    },
}
