TEXTS = {
    "en": {
        "welcome": "Welcome!",
        "menu_title": "Menu. Choose an action:",
        "mode_usage": "Usage: /mode rss OR /mode creator OR /mode both",
        "btn_lang": "🌐 Language",
        "choose_lang": "Choose your language:",
        "btn_setup": "🛠 Setup",
        "btn_modes": "🧠 Modes",
        "btn_payment": "💳 Payment",
        "btn_help": "❓ Help",
        "btn_status": "ℹ️ Status",
        "btn_setchannel": "📌 Set channel",
        "btn_unsetchannel": "🧹 Unset channel",
        "btn_addfeed": "🧾 Add feed",
        "btn_deletefeed": "🗑 Delete feed",
        "btn_setstyle": "✍️ Set style",
        "btn_showstyle": "📄 Show style",
        "btn_resetstyle": "♻️ Reset style",
        "btn_on": "🤖 Autopost ON",
        "btn_off": "🛑 OFF",
        "btn_back": "⬅ Back",
        "modes_help": "Choose mode with commands:\n/mode rss\n/mode creator\n/mode both",
    },
    "ru": {
        "welcome": "Добро пожаловать!",
        "menu_title": "Меню. Выберите действие:",
        "mode_usage": "Использование: /mode rss ИЛИ /mode creator ИЛИ /mode both",
        "btn_lang": "🌐 Язык",
        "choose_lang": "Выберите язык:",
        "btn_setup": "🛠 Настройка",
        "btn_modes": "🧠 Режимы",
        "btn_payment": "💳 Оплата",
        "btn_help": "❓ Помощь",
        "btn_status": "ℹ️ Статус",
        "btn_setchannel": "📌 Канал",
        "btn_unsetchannel": "🧹 Отключить канал",
        "btn_addfeed": "🧾 Лента (RSS)",
        "btn_deletefeed": "🗑 Удалить ленту",
        "btn_setstyle": "✍️ Стиль",
        "btn_showstyle": "📄 Показать стиль",
        "btn_resetstyle": "♻️ Сбросить стиль",
        "btn_on": "🤖 Автопост ВКЛ",
        "btn_off": "🛑 ВЫКЛ",
        "btn_back": "⬅ Назад",
        "modes_help": "Выберите режим командами:\n/mode rss\n/mode creator\n/mode both",
    },
}
