TEXTS = {
    "en": {
        "welcome": "Welcome!",
        "menu_title": "Menu. Choose an action:",
        "mode_usage": "Usage: /mode rss OR /mode creator OR /mode both",
        "btn_setup": "🛠 Setup",
        "btn_modes": "🧠 Modes",
        "btn_pay": "💳 Payment",
        "btn_help": "❓ Help",
        "btn_status": "ℹ️ Status",
        "btn_lang": "🌐 Language",
        "btn_setchannel": "📌 Set channel",
        "btn_unsetchannel": "🧹 Unset channel",
        "btn_addfeed": "🧾 Add feed",
        "btn_deletefeed": "🗑 Delete feed",
        "btn_setstyle": "✍️ Set style",
        "btn_showstyle": "📄 Show style",
        "btn_resetstyle": "♻️ Reset style",
        "btn_autopost_on": "🤖 Autopost: ON",
        "btn_autopost_off": "🤖 Autopost: OFF",
        "btn_back": "⬅ Back",
        "setup_title": "🛠 Setup. Choose an action:",
        "help_screen": "❓ Help\n\nContacts: @a_karaglan, @a_karaglanov\nGuide: https://telegra.ph/Instrukciya-po-polzovaniyu-botom-i-poleznye-materialy-02-27",
    },
    "ru": {
        "welcome": "Добро пожаловать!",
        "menu_title": "Меню. Выберите действие:",
        "mode_usage": "Использование: /mode rss ИЛИ /mode creator ИЛИ /mode both",
        "btn_setup": "🛠 Настройка",
        "btn_modes": "🧠 Режимы",
        "btn_pay": "💳 Оплата",
        "btn_help": "❓ Помощь",
        "btn_status": "ℹ️ Статус",
        "btn_lang": "🌐 Язык",
        "btn_setchannel": "📌 Канал",
        "btn_unsetchannel": "🧹 Отключить канал",
        "btn_addfeed": "🧾 Лента (RSS)",
        "btn_deletefeed": "🗑 Удалить ленту",
        "btn_setstyle": "✍️ Стиль",
        "btn_showstyle": "📄 Показать стиль",
        "btn_resetstyle": "♻️ Сбросить стиль",
        "btn_autopost_on": "🤖 Автопост: ВКЛ",
        "btn_autopost_off": "🤖 Автопост: ВЫКЛ",
        "btn_back": "⬅ Назад",
        "setup_title": "🛠 Настройка. Выберите действие:",
        "help_screen": "❓ Помощь\n\nКонтакты: @a_karaglan, @a_karaglanov\nГайд: https://telegra.ph/Instrukciya-po-polzovaniyu-botom-i-poleznye-materialy-02-27",
    },
}
